/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as CrearRouteImport } from './routes/crear'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as NuevaClaveRouteImport } from './routes/nueva-clave'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as SonidoIdRouteImport } from './routes/sonido.$id'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as UUserRouteImport } from './routes/u.$user'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearRoute = CrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaClaveRoute = NuevaClaveRouteImport.update({
  id: '/nueva-clave',
  path: '/nueva-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SonidoIdRoute = SonidoIdRouteImport.update({
  id: '/sonido/$id',
  path: '/sonido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserRoute = UUserRouteImport.update({
  id: '/u/$user',
  path: '/u/$user',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/buscar': typeof BuscarRoute
  '/comunidad': typeof ComunidadRoute
  '/crear': typeof CrearRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/inbox': typeof InboxRoute
  '/nueva-clave': typeof NuevaClaveRoute
  '/perfil': typeof PerfilRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/c/$id': typeof CIdRoute
  '/sonido/$id': typeof SonidoIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/u/$user': typeof UUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/buscar': typeof BuscarRoute
  '/comunidad': typeof ComunidadRoute
  '/crear': typeof CrearRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/inbox': typeof InboxRoute
  '/nueva-clave': typeof NuevaClaveRoute
  '/perfil': typeof PerfilRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/c/$id': typeof CIdRoute
  '/sonido/$id': typeof SonidoIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/u/$user': typeof UUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/buscar': typeof BuscarRoute
  '/comunidad': typeof ComunidadRoute
  '/crear': typeof CrearRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/inbox': typeof InboxRoute
  '/nueva-clave': typeof NuevaClaveRoute
  '/perfil': typeof PerfilRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/c/$id': typeof CIdRoute
  '/sonido/$id': typeof SonidoIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/u/$user': typeof UUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/buscar'
    | '/comunidad'
    | '/crear'
    | '/entrar'
    | '/explorar'
    | '/inbox'
    | '/nueva-clave'
    | '/perfil'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/terminos'
    | '/c/$id'
    | '/sonido/$id'
    | '/tag/$tag'
    | '/u/$user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/buscar'
    | '/comunidad'
    | '/crear'
    | '/entrar'
    | '/explorar'
    | '/inbox'
    | '/nueva-clave'
    | '/perfil'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/terminos'
    | '/c/$id'
    | '/sonido/$id'
    | '/tag/$tag'
    | '/u/$user'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/buscar'
    | '/comunidad'
    | '/crear'
    | '/entrar'
    | '/explorar'
    | '/inbox'
    | '/nueva-clave'
    | '/perfil'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/terminos'
    | '/c/$id'
    | '/sonido/$id'
    | '/tag/$tag'
    | '/u/$user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  BuscarRoute: typeof BuscarRoute
  ComunidadRoute: typeof ComunidadRoute
  CrearRoute: typeof CrearRoute
  EntrarRoute: typeof EntrarRoute
  ExplorarRoute: typeof ExplorarRoute
  InboxRoute: typeof InboxRoute
  NuevaClaveRoute: typeof NuevaClaveRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  TerminosRoute: typeof TerminosRoute
  CIdRoute: typeof CIdRoute
  SonidoIdRoute: typeof SonidoIdRoute
  TagTagRoute: typeof TagTagRoute
  UUserRoute: typeof UUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear': {
      id: '/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof CrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-clave': {
      id: '/nueva-clave'
      path: '/nueva-clave'
      fullPath: '/nueva-clave'
      preLoaderRoute: typeof NuevaClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sonido/$id': {
      id: '/sonido/$id'
      path: '/sonido/$id'
      fullPath: '/sonido/$id'
      preLoaderRoute: typeof SonidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$user': {
      id: '/u/$user'
      path: '/u/$user'
      fullPath: '/u/$user'
      preLoaderRoute: typeof UUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  BuscarRoute: BuscarRoute,
  ComunidadRoute: ComunidadRoute,
  CrearRoute: CrearRoute,
  EntrarRoute: EntrarRoute,
  ExplorarRoute: ExplorarRoute,
  InboxRoute: InboxRoute,
  NuevaClaveRoute: NuevaClaveRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadRoute: PrivacidadRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  TerminosRoute: TerminosRoute,
  CIdRoute: CIdRoute,
  SonidoIdRoute: SonidoIdRoute,
  TagTagRoute: TagTagRoute,
  UUserRoute: UUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
