import { seedClipVideoUrl } from "./media";
import { region } from "./region";
import { CALENDAR_CLIPS, inferCountry, inferSeries, type ClipCountry, type SeriesId } from "./culture";

export type Comment = { user: string; text: string };

export type Clip = {
  id: string;
  user: string;
  displayName: string;
  caption: string;
  city: string;
  image: string;
  video?: string;
  likes: number;
  comments: Comment[];
  tags: string[];
  sound: string;
  soundArtist: string;
  following?: boolean;
  live?: boolean;
  viewers?: number;
  shares?: number;
  friend?: boolean;
  series?: SeriesId;
  country?: ClipCountry;
};

const RAW_CLIPS: Clip[] = [
  {
    id: "tacos",
    user: "chile_y_lima",
    displayName: "Chile y Lima",
    caption: "Pastor a las 2am en la Roma. Si no hay piña, no es pastor.",
    city: "Ciudad de México",
    image: "/clips/tacos.jpg",
    likes: 12400,
    comments: [
      { user: "taquero.sur", text: "¿Cuál taquería?" },
      { user: "hambre.mx", text: "Se me antojó feo" },
      { user: "roma.norte", text: "Roma best colonia" },
    ],
    tags: ["tacos", "CDMX", "parati"],
    sound: "Pastor a las 2",
    soundArtist: "Sonido Roma",
  },
  {
    id: "trompo",
    user: "chile_y_lima",
    displayName: "Chile y Lima",
    caption: "El trompo no miente. Naranja, piña, y la fila que da la vuelta.",
    city: "Ciudad de México",
    image: "/clips/trompo.jpg",
    likes: 18900,
    comments: [{ user: "noche.cdmx", text: "Esa luz es de iglesia" }],
    tags: ["tacos", "CDMX", "comida"],
    sound: "Trompo mix",
    soundArtist: "Sonido Roma",
    live: true,
    viewers: 1840,
  },
  {
    id: "gdl",
    user: "guadalajara.nights",
    displayName: "GDL Nights",
    caption: "Papel picado, calle viva. Jalisco no es México — es otra cosa.",
    city: "Guadalajara",
    image: "/clips/gdl.jpg",
    likes: 8100,
    comments: [
      { user: "tapatia", text: "Jalisco es México" },
      { user: "centro.gdl", text: "¿En qué calle?" },
    ],
    tags: ["Guadalajara", "parati"],
    sound: "Calle viva",
    soundArtist: "Banda Jalisco",
    following: true,
  },
  {
    id: "monterrey",
    user: "norteno.mx",
    displayName: "Norteño",
    caption: "El Cerro de la Silla no pide permiso. Siempre está.",
    city: "Monterrey",
    image: "/clips/monterrey.jpg",
    likes: 6700,
    comments: [{ user: "mty.pride", text: "Orgullo regiomontano" }],
    tags: ["Monterrey", "MTY"],
    sound: "Banda del Cerro",
    soundArtist: "Norteño MX",
    following: true,
  },
  {
    id: "merida",
    user: "yucatan.sabor",
    displayName: "Yucatán Sabor",
    caption: "Arco de San Juan. Cochinita después, si aguantas el calor.",
    city: "Mérida",
    image: "/clips/merida.jpg",
    likes: 9900,
    comments: [{ user: "peninsula", text: "Con cebolla morada o nada" }],
    tags: ["Merida", "Yucatan"],
    sound: "Trova de mediodía",
    soundArtist: "Yucatán Sabor",
  },
  {
    id: "zocalo",
    user: "centro.cdmx",
    displayName: "Centro CDMX",
    caption: "Catedral de noche. El Zócalo nunca duerme del todo.",
    city: "Ciudad de México",
    image: "/clips/zocalo.jpg",
    likes: 15200,
    comments: [{ user: "noctambulo", text: "Esa luz pega distinto" }],
    tags: ["CDMX", "zocalo"],
    sound: "Cumbia del Zócalo",
    soundArtist: "Centro CDMX",
    live: true,
    viewers: 920,
  },
  {
    id: "playa",
    user: "caribe.ojo",
    displayName: "Caribe Ojo",
    caption: "El Caribe no es filtro. Es así.",
    city: "Quintana Roo",
    image: "/clips/playa.jpg",
    likes: 22100,
    comments: [{ user: "playa.fan", text: "Ya quiero ir" }],
    tags: ["playa", "caribe"],
    sound: "Dembow Caribe",
    soundArtist: "Caribe Ojo",
  },
  {
    id: "cancun",
    user: "zona.hotelera",
    displayName: "Zona Hotelera",
    caption: "Cancún desde arriba. Turquesa de verdad.",
    city: "Cancún",
    image: "/clips/cancun.jpg",
    likes: 18800,
    comments: [{ user: "qroo", text: "Clásico" }],
    tags: ["Cancun", "playa"],
    sound: "House Hotelera",
    soundArtist: "Zona Hotelera",
    following: true,
  },
  {
    id: "puebla",
    user: "puebla.mole",
    displayName: "Puebla Mole",
    caption: "Mole que sí sabe a casa. Puebla no perdona mediocre.",
    city: "Puebla",
    image: "/clips/puebla.jpg",
    likes: 5400,
    comments: [{ user: "angelopolis", text: "Con arroz, por favor" }],
    tags: ["Puebla", "comida"],
    sound: "Son de Puebla",
    soundArtist: "Puebla Mole",
  },
  {
    id: "mercado",
    user: "tianguis.vivo",
    displayName: "Tianguis Vivo",
    caption: "Textiles, sol, cobblestone. El tianguis manda.",
    city: "Puebla",
    image: "/clips/mercado.jpg",
    likes: 4300,
    comments: [{ user: "artesana", text: "Me llevo el rebozo" }],
    tags: ["mercado", "Puebla"],
    sound: "Huapango tianguis",
    soundArtist: "Tianguis Vivo",
  },
  {
    id: "lucha",
    user: "arena.mexico",
    displayName: "Arena México",
    caption: "Tercera caída. Si no gritas, no estabas.",
    city: "Ciudad de México",
    image: "/clips/lucha.jpg",
    likes: 30100,
    comments: [
      { user: "rudo.oficial", text: "Esa máscara es leyenda" },
      { user: "tecnico", text: "Tercera caída siempre" },
    ],
    tags: ["lucha", "CDMX", "parati"],
    sound: "Campana de arena",
    soundArtist: "Arena México",
    live: true,
    viewers: 4120,
  },
  {
    id: "tulum",
    user: "caribe.ojo",
    displayName: "Caribe Ojo",
    caption: "Tulum sin influencer. Solo piedra, mar y el sol que pega.",
    city: "Tulum",
    image: "/clips/tulum.jpg",
    likes: 27400,
    comments: [{ user: "mayan.coast", text: "Esto sí es Quintana Roo" }],
    tags: ["playa", "Tulum", "caribe"],
    sound: "Selva Tulum",
    soundArtist: "Caribe Ojo",
  },
  {
    id: "oaxaca",
    user: "istmo.luz",
    displayName: "Istmo Luz",
    caption: "Oaxaca al atardecer. El papel picado ya es parte del cielo.",
    city: "Oaxaca",
    image: "/clips/oaxaca.jpg",
    likes: 14200,
    comments: [{ user: "mezcal.claro", text: "¿En Santo Domingo?" }],
    tags: ["Oaxaca", "parati"],
    sound: "Son istmeño",
    soundArtist: "Istmo Luz",
    following: true,
  },
  {
    id: "bellas",
    user: "centro.cdmx",
    displayName: "Centro CDMX",
    caption: "Bellas Artes después de la lluvia. El mármol se ve de oro.",
    city: "Ciudad de México",
    image: "/clips/bellas.jpg",
    likes: 19800,
    comments: [{ user: "cultura.mx", text: "Esta ciudad no se acaba" }],
    tags: ["CDMX", "cultura"],
    sound: "Nocturno Bellas Artes",
    soundArtist: "Centro CDMX",
  },
  {
    id: "alebrijes",
    user: "tianguis.vivo",
    displayName: "Tianguis Vivo",
    caption: "Alebrijes que te miran de vuelta. Hecho a mano, no de souvenir.",
    city: "Oaxaca",
    image: "/clips/alebrijes.jpg",
    likes: 8700,
    comments: [{ user: "taller.oax", text: "Ese jaguar está vivo" }],
    tags: ["Oaxaca", "mercado", "arte"],
    sound: "Alebrije beat",
    soundArtist: "Tianguis Vivo",
  },
];

const EDITORIAL_CLIPS: Clip[] = [
  {
    id: "ind-grito",
    user: "otealo",
    displayName: "Otealo",
    caption: "El 15 de noche. El Zócalo no pide permiso: ¡Viva México!",
    city: "Ciudad de México",
    image: "/clips/ind-grito.jpg",
    video: "/clips/ind-grito.mp4",
    likes: 0,
    comments: [],
    tags: ["independencia", "grito", "CDMX", "parati"],
    sound: "Viva México",
    soundArtist: "Plaza de la Constitución",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "ind-campana",
    user: "otealo",
    displayName: "Otealo",
    caption: "Dolores Hidalgo, 1810. La campana todavía suena.",
    city: "Guanajuato",
    image: "/clips/ind-campana.jpg",
    video: "/clips/ind-campana.mp4",
    likes: 0,
    comments: [],
    tags: ["independencia", "grito", "historia", "parati"],
    sound: "Campana de Dolores",
    soundArtist: "Parroquia de Dolores",
    series: "HistorySnack",
    country: "MX",
  },
  {
    id: "ind-nogada",
    user: "otealo",
    displayName: "Otealo",
    caption: "Chile en nogada. Verde, blanco, rojo: se come la bandera.",
    city: "Puebla",
    image: "/clips/ind-nogada.jpg",
    video: "/clips/ind-nogada.mp4",
    likes: 0,
    comments: [],
    tags: ["independencia", "comida", "nogada", "parati"],
    sound: "Nuez y granada",
    soundArtist: "Cocina poblana",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "ind-desfile",
    user: "otealo",
    displayName: "Otealo",
    caption: "El 16 es el desfile. El Grito fue anoche. No los revuelvas.",
    city: "Ciudad de México",
    image: "/clips/ind-desfile.jpg",
    video: "/clips/ind-desfile.mp4",
    likes: 0,
    comments: [],
    tags: ["independencia", "mito", "CDMX", "parati"],
    sound: "Reforma de mañana",
    soundArtist: "Ángel de la Independencia",
    series: "MythsVsFacts",
    country: "MX",
  },
  {
    id: "ind-papel",
    user: "otealo",
    displayName: "Otealo",
    caption: "Papel picado en la cuadra. Así se siente el 15 en el barrio.",
    city: "Ciudad de México",
    image: "/clips/ind-papel.jpg",
    video: "/clips/ind-papel.mp4",
    likes: 0,
    comments: [],
    tags: ["independencia", "fiesta", "CDMX", "parati"],
    sound: "Calle tricolor",
    soundArtist: "La cuadra",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "pastor2",
    user: "otealo",
    displayName: "Otealo",
    caption: "Pastor que no duerme. Roma Norte, 1am.",
    city: "Ciudad de México",
    image: "/clips/pastor2.jpg",
    likes: 0,
    comments: [],
    tags: ["tacos", "CDMX", "parati"],
    sound: "Trompo de noche",
    soundArtist: "Otealo",
  },
  {
    id: "mariachi",
    user: "otealo",
    displayName: "Otealo",
    caption: "El Grito no pide permiso. Plaza y trompeta.",
    city: "Guadalajara",
    image: "/clips/mariachi.jpg",
    likes: 0,
    comments: [],
    tags: ["musica", "mariachi", "parati"],
    sound: "Son de plaza",
    soundArtist: "Otealo",
  },
  {
    id: "caribe",
    user: "otealo",
    displayName: "Otealo",
    caption: "El Caribe no es filtro. Es así.",
    city: "Cancún",
    image: "/clips/caribe.jpg",
    likes: 0,
    comments: [],
    tags: ["playa", "caribe", "parati"],
    sound: "Ola turquesa",
    soundArtist: "Otealo",
  },
  {
    id: "lucha2",
    user: "otealo",
    displayName: "Otealo",
    caption: "Máscara, tercera caída, la gente de pie.",
    city: "Ciudad de México",
    image: "/clips/lucha2.jpg",
    likes: 0,
    comments: [],
    tags: ["lucha", "CDMX", "parati"],
    sound: "Campana arena",
    soundArtist: "Otealo",
  },
  {
    id: "mercado2",
    user: "otealo",
    displayName: "Otealo",
    caption: "Mole, cempasúchil y alebrijes que te miran.",
    city: "Oaxaca",
    image: "/clips/mercado2.jpg",
    likes: 0,
    comments: [],
    tags: ["mercado", "oaxaca", "parati"],
    sound: "Tianguis vivo",
    soundArtist: "Otealo",
  },
  {
    id: "zocalo2",
    user: "otealo",
    displayName: "Otealo",
    caption: "La Catedral se enciende y el Zócalo sigue.",
    city: "Ciudad de México",
    image: "/clips/zocalo2.jpg",
    likes: 0,
    comments: [],
    tags: ["CDMX", "zocalo", "parati"],
    sound: "Campanas de noche",
    soundArtist: "Otealo",
  },
  {
    id: "gdl2",
    user: "otealo",
    displayName: "Otealo",
    caption: "Guadalajara de noche. La plaza no se acaba.",
    city: "Guadalajara",
    image: "/clips/gdl2.jpg",
    likes: 0,
    comments: [],
    tags: ["guadalajara", "parati"],
    sound: "Tapatía",
    soundArtist: "Otealo",
  },
  {
    id: "chichen",
    user: "otealo",
    displayName: "Otealo",
    caption: "Kukulcán no necesita filtro.",
    city: "Yucatán",
    image: "/clips/chichen.jpg",
    likes: 0,
    comments: [],
    tags: ["yucatan", "parati"],
    sound: "Sol maya",
    soundArtist: "Otealo",
  },
  {
    id: "paletas",
    user: "otealo",
    displayName: "Otealo",
    caption: "Paleta, sol, y la playa al fondo.",
    city: "Quintana Roo",
    image: "/clips/paletas.jpg",
    likes: 0,
    comments: [],
    tags: ["playa", "parati"],
    sound: "Carrito dulce",
    soundArtist: "Otealo",
  },
  {
    id: "metro",
    user: "otealo",
    displayName: "Otealo",
    caption: "Insurgentes. Naranja, prisa, México.",
    city: "Ciudad de México",
    image: "/clips/metro.jpg",
    likes: 0,
    comments: [],
    tags: ["CDMX", "metro", "parati"],
    sound: "Andén naranja",
    soundArtist: "Otealo",
  },
  {
    id: "sanmiguel",
    user: "otealo",
    displayName: "Otealo",
    caption: "Lluvia en adoquín. San Miguel se ve de oro.",
    city: "Guanajuato",
    image: "/clips/sanmiguel.jpg",
    likes: 0,
    comments: [],
    tags: ["sanmiguel", "parati"],
    sound: "Lluvia colonial",
    soundArtist: "Otealo",
  },
  {
    id: "futbol",
    user: "otealo",
    displayName: "Otealo",
    caption: "La afición es el onceavo.",
    city: "Ciudad de México",
    image: "/clips/futbol.jpg",
    likes: 0,
    comments: [],
    tags: ["futbol", "parati"],
    sound: "Cántico verde",
    soundArtist: "Otealo",
  },
  {
    id: "xochi",
    user: "otealo",
    displayName: "Otealo",
    caption: "Trajinera, cempasúchil, y el canal que no se acaba.",
    city: "Ciudad de México",
    image: "/clips/xochi.jpg",
    likes: 0,
    comments: [],
    tags: ["xochimilco", "CDMX", "parati"],
    sound: "Canal de flores",
    soundArtist: "Otealo",
  },
  {
    id: "teoti",
    user: "otealo",
    displayName: "Otealo",
    caption: "Calzada de los Muertos. El sol pega distinto.",
    city: "Estado de México",
    image: "/clips/teoti.jpg",
    likes: 0,
    comments: [],
    tags: ["teotihuacan", "parati"],
    sound: "Sol de pirámide",
    soundArtist: "Otealo",
  },
  {
    id: "coyoacan",
    user: "otealo",
    displayName: "Otealo",
    caption: "Coyoacán de jacaranda. La calle es el filtro.",
    city: "Ciudad de México",
    image: "/clips/coyoacan.jpg",
    likes: 0,
    comments: [],
    tags: ["coyoacan", "CDMX", "parati"],
    sound: "Bici en cobble",
    soundArtist: "Otealo",
  },
  {
    id: "mezcal",
    user: "otealo",
    displayName: "Otealo",
    caption: "Mezcal que huele a pueblo. Copita y ya.",
    city: "Oaxaca",
    image: "/clips/mezcal.jpg",
    likes: 0,
    comments: [],
    tags: ["mezcal", "oaxaca", "parati"],
    sound: "Copita humeante",
    soundArtist: "Otealo",
  },
  {
    id: "cabo",
    user: "otealo",
    displayName: "Otealo",
    caption: "El Arco no se cansa de pelear con el mar.",
    city: "Los Cabos",
    image: "/clips/cabo.jpg",
    likes: 0,
    comments: [],
    tags: ["cabo", "playa", "parati"],
    sound: "Rompeolas",
    soundArtist: "Otealo",
  },
  {
    id: "chapu",
    user: "otealo",
    displayName: "Otealo",
    caption: "Chapultepec en lancha. Fin de semana mexicano.",
    city: "Ciudad de México",
    image: "/clips/chapu.jpg",
    likes: 0,
    comments: [],
    tags: ["chapultepec", "CDMX", "parati"],
    sound: "Lago del bosque",
    soundArtist: "Otealo",
  },
  {
    id: "tamales",
    user: "otealo",
    displayName: "Otealo",
    caption: "Tamales a las 7am. El vapor no miente.",
    city: "Ciudad de México",
    image: "/clips/tamales.jpg",
    likes: 0,
    comments: [],
    tags: ["tamales", "CDMX", "parati"],
    sound: "Olla de vapor",
    soundArtist: "Otealo",
  },
  {
    id: "folklor",
    user: "otealo",
    displayName: "Otealo",
    caption: "La falda da la vuelta y Jalisco aplaude.",
    city: "Guadalajara",
    image: "/clips/folklor.jpg",
    likes: 0,
    comments: [],
    tags: ["folklor", "jalisco", "parati"],
    sound: "Zapateado",
    soundArtist: "Otealo",
  },
  {
    id: "cenote",
    user: "otealo",
    displayName: "Otealo",
    caption: "Cenote. El sol entra por un hueco y ya es iglesia.",
    city: "Yucatán",
    image: "/clips/cenote.jpg",
    likes: 0,
    comments: [],
    tags: ["cenote", "yucatan", "parati"],
    sound: "Agua sagrada",
    soundArtist: "Otealo",
  },
  {
    id: "agave",
    user: "otealo",
    displayName: "Otealo",
    caption: "Agave hasta el volcán. Jalisco de verdad.",
    city: "Jalisco",
    image: "/clips/agave.jpg",
    likes: 0,
    comments: [],
    tags: ["tequila", "jalisco", "parati"],
    sound: "Campo azul",
    soundArtist: "Otealo",
  },
  {
    id: "vallarta",
    user: "otealo",
    displayName: "Otealo",
    caption: "Malecón de Vallarta. El sol se rinde despacio.",
    city: "Puerto Vallarta",
    image: "/clips/vallarta.jpg",
    likes: 0,
    comments: [],
    tags: ["vallarta", "playa", "parati"],
    sound: "Atardecer malecón",
    soundArtist: "Otealo",
  },
  {
    id: "taxco",
    user: "otealo",
    displayName: "Otealo",
    caption: "Taxco se cuelga de la montaña. Plata y campanas.",
    city: "Guerrero",
    image: "/clips/taxco.jpg",
    likes: 0,
    comments: [],
    tags: ["taxco", "parati"],
    sound: "Cerro de plata",
    soundArtist: "Otealo",
  },
  {
    id: "bacalar",
    user: "otealo",
    displayName: "Otealo",
    caption: "Bacalar. Siete azules y un muelle que no miente.",
    city: "Quintana Roo",
    image: "/clips/bacalar.jpg",
    likes: 0,
    comments: [],
    tags: ["bacalar", "playa", "parati"],
    sound: "Laguna de siete",
    soundArtist: "Otealo",
  },
  {
    id: "palenque",
    user: "otealo",
    displayName: "Otealo",
    caption: "Palenque sale de la selva. Piedra y niebla.",
    city: "Chiapas",
    image: "/clips/palenque.jpg",
    likes: 0,
    comments: [],
    tags: ["palenque", "parati"],
    sound: "Templo en verde",
    soundArtist: "Otealo",
  },
  {
    id: "campeche",
    user: "otealo",
    displayName: "Otealo",
    caption: "Campeche de pastel. La muralla todavía vigila.",
    city: "Campeche",
    image: "/clips/campeche.jpg",
    likes: 0,
    comments: [],
    tags: ["campeche", "parati"],
    sound: "Baluarte",
    soundArtist: "Otealo",
  },
  {
    id: "guanajuato",
    user: "otealo",
    displayName: "Otealo",
    caption: "Guanajuato se apila. Callejón y color.",
    city: "Guanajuato",
    image: "/clips/guanajuato.jpg",
    likes: 0,
    comments: [],
    tags: ["guanajuato", "parati"],
    sound: "Callejón del beso",
    soundArtist: "Otealo",
  },
  {
    id: "elote",
    user: "otealo",
    displayName: "Otealo",
    caption: "Elote con chile. La calle es el comedor.",
    city: "Ciudad de México",
    image: "/clips/elote.jpg",
    likes: 0,
    comments: [],
    tags: ["elote", "CDMX", "parati"],
    sound: "Carrito de maíz",
    soundArtist: "Otealo",
  },
  {
    id: "monarca",
    user: "otealo",
    displayName: "Otealo",
    caption: "Mariposa monarca. Michoacán se mueve entero.",
    city: "Michoacán",
    image: "/clips/monarca.jpg",
    likes: 0,
    comments: [],
    tags: ["monarca", "michoacan", "parati"],
    sound: "Bosque naranja",
    soundArtist: "Otealo",
  },
  {
    id: "hierve",
    user: "otealo",
    displayName: "Otealo",
    caption: "Hierve el Agua. La montaña se petrificó.",
    city: "Oaxaca",
    image: "/clips/hierve.jpg",
    likes: 0,
    comments: [],
    tags: ["hierve", "oaxaca", "parati"],
    sound: "Cascada de piedra",
    soundArtist: "Otealo",
  },
  {
    id: "bernal",
    user: "otealo",
    displayName: "Otealo",
    caption: "Peña de Bernal. Un pueblo al pie de un diente.",
    city: "Querétaro",
    image: "/clips/bernal.jpg",
    likes: 0,
    comments: [],
    tags: ["bernal", "parati"],
    sound: "Monolito",
    soundArtist: "Otealo",
  },
  {
    id: "sumidero",
    user: "otealo",
    displayName: "Otealo",
    caption: "Cañón del Sumidero. El río cabe entre dos paredes.",
    city: "Chiapas",
    image: "/clips/sumidero.jpg",
    likes: 0,
    comments: [],
    tags: ["sumidero", "parati"],
    sound: "Pared de selva",
    soundArtist: "Otealo",
  },
  {
    id: "churros",
    user: "otealo",
    displayName: "Otealo",
    caption: "Churro y chocolate. La noche se endulza.",
    city: "Ciudad de México",
    image: "/clips/churros.jpg",
    likes: 0,
    comments: [],
    tags: ["churros", "CDMX", "parati"],
    sound: "Azúcar caliente",
    soundArtist: "Otealo",
  },
  {
    id: "reforma",
    user: "otealo",
    displayName: "Otealo",
    caption: "Reforma se enciende. El Ángel no se mueve.",
    city: "Ciudad de México",
    image: "/clips/reforma.jpg",
    likes: 0,
    comments: [],
    tags: ["reforma", "CDMX", "parati"],
    sound: "Ángel de noche",
    soundArtist: "Otealo",
  },
  {
    id: "tijuana",
    user: "otealo",
    displayName: "Otealo",
    caption: "Playas de Tijuana. El Pacífico también es México.",
    city: "Tijuana",
    image: "/clips/tijuana.jpg",
    likes: 0,
    comments: [],
    tags: ["tijuana", "playa", "parati"],
    sound: "Faro del norte",
    soundArtist: "Otealo",
  },
  {
    id: "barriofut",
    user: "otealo",
    displayName: "Otealo",
    caption: "Fútbol de barrio. Un balón y una pared alcanzan.",
    city: "Ciudad de México",
    image: "/clips/barriofut.jpg",
    likes: 0,
    comments: [],
    tags: ["futbol", "CDMX", "parati"],
    sound: "Cancha de concreto",
    soundArtist: "Otealo",
  },
  {
    id: "azteca",
    user: "otealo",
    displayName: "Otealo",
    caption: "El Azteca se enciende. Aquí late el fútbol.",
    city: "Ciudad de México",
    image: "/clips/azteca.jpg",
    likes: 0,
    comments: [],
    tags: ["futbol", "azteca", "parati"],
    sound: "Luces del estadio",
    soundArtist: "Otealo",
  },
  {
    id: "aficion",
    user: "otealo",
    displayName: "Otealo",
    caption: "Verde, blanco, rojo. La afición es el onceavo.",
    city: "Ciudad de México",
    image: "/clips/aficion.jpg",
    likes: 0,
    comments: [],
    tags: ["futbol", "parati"],
    sound: "Grito de tribuna",
    soundArtist: "Otealo",
  },
  {
    id: "playafut",
    user: "otealo",
    displayName: "Otealo",
    caption: "Fútbol en la playa. El gol se celebra con arena.",
    city: "Quintana Roo",
    image: "/clips/playafut.jpg",
    likes: 0,
    comments: [],
    tags: ["futbol", "playa", "parati"],
    sound: "Pelota y oleaje",
    soundArtist: "Otealo",
  },
  {
    id: "templomayor",
    user: "otealo",
    displayName: "Otealo",
    caption: "Templo Mayor. Tenochtitlan debajo de la catedral.",
    city: "Ciudad de México",
    image: "/clips/templomayor.jpg",
    likes: 0,
    comments: [],
    tags: ["azteca", "mexica", "parati"],
    sound: "Serpiente de piedra",
    soundArtist: "Otealo",
  },
  {
    id: "piramidesol",
    user: "otealo",
    displayName: "Otealo",
    caption: "Pirámide del Sol. Teotihuacan no se acaba de subir.",
    city: "Estado de México",
    image: "/clips/piramidesol.jpg",
    likes: 0,
    comments: [],
    tags: ["teotihuacan", "piramide", "parati"],
    sound: "Escalón de sol",
    soundArtist: "Otealo",
  },
  {
    id: "cholula",
    user: "otealo",
    displayName: "Otealo",
    caption: "Cholula. Una iglesia encima de la pirámide más grande.",
    city: "Puebla",
    image: "/clips/cholula.jpg",
    likes: 0,
    comments: [],
    tags: ["cholula", "piramide", "parati"],
    sound: "Cerro sagrado",
    soundArtist: "Otealo",
  },
  {
    id: "uxmal",
    user: "otealo",
    displayName: "Otealo",
    caption: "Uxmal. La Pirámide del Adivino no es un triángulo.",
    city: "Yucatán",
    image: "/clips/uxmal.jpg",
    likes: 0,
    comments: [],
    tags: ["uxmal", "maya", "parati"],
    sound: "Pirámide oval",
    soundArtist: "Otealo",
  },
  {
    id: "montealban",
    user: "otealo",
    displayName: "Otealo",
    caption: "Monte Albán. Las pirámides miran todo el valle.",
    city: "Oaxaca",
    image: "/clips/montealban.jpg",
    likes: 0,
    comments: [],
    tags: ["montealban", "piramide", "parati"],
    sound: "Terraza zapoteca",
    soundArtist: "Otealo",
  },
  {
    id: "tajin",
    user: "otealo",
    displayName: "Otealo",
    caption: "El Tajín. Nichos de piedra y Veracruz verde.",
    city: "Veracruz",
    image: "/clips/tajin.jpg",
    likes: 0,
    comments: [],
    tags: ["tajin", "piramide", "parati"],
    sound: "Pirámide de nichos",
    soundArtist: "Otealo",
  },
  {
    id: "concheros",
    user: "otealo",
    displayName: "Otealo",
    caption: "Danza Mexica. El Zócalo todavía es Tenochtitlan.",
    city: "Ciudad de México",
    image: "/clips/concheros.jpg",
    likes: 0,
    comments: [],
    tags: ["azteca", "mexica", "parati"],
    sound: "Tambor y pluma",
    soundArtist: "Otealo",
  },
  {
    id: "castillo",
    user: "otealo",
    displayName: "Otealo",
    caption: "El Castillo de Tulum. Templo, acantilado, Caribe.",
    city: "Tulum",
    image: "/clips/castillo.jpg",
    likes: 0,
    comments: [],
    tags: ["tulum", "maya", "parati"],
    sound: "Templo al mar",
    soundArtist: "Otealo",
  },
  {
    id: "kukulkan",
    user: "otealo",
    displayName: "Otealo",
    caption: "Kukulcán baja por la escalera. Chichén no es leyenda.",
    city: "Yucatán",
    image: "/clips/kukulkan.jpg",
    likes: 0,
    comments: [],
    tags: ["maya", "chichen", "parati"],
    sound: "Serpiente de sol",
    soundArtist: "Otealo",
  },
  {
    id: "coba",
    user: "otealo",
    displayName: "Otealo",
    caption: "Cobá. La pirámide sale de la selva y no pide permiso.",
    city: "Quintana Roo",
    image: "/clips/coba.jpg",
    likes: 0,
    comments: [],
    tags: ["maya", "coba", "parati"],
    sound: "Nohoch Mul",
    soundArtist: "Otealo",
  },
  {
    id: "calakmul",
    user: "otealo",
    displayName: "Otealo",
    caption: "Calakmul. Dos templos sobre el dosel. El reino escondido.",
    city: "Campeche",
    image: "/clips/calakmul.jpg",
    likes: 0,
    comments: [],
    tags: ["maya", "calakmul", "parati"],
    sound: "Selva de reyes",
    soundArtist: "Otealo",
  },
  {
    id: "bonampak",
    user: "otealo",
    displayName: "Otealo",
    caption: "Bonampak. Los mayas se pintaron vivos en la piedra.",
    city: "Chiapas",
    image: "/clips/bonampak.jpg",
    likes: 0,
    comments: [],
    tags: ["maya", "bonampak", "parati"],
    sound: "Mural de guerra",
    soundArtist: "Otealo",
  },
  {
    id: "olmec",
    user: "otealo",
    displayName: "Otealo",
    caption: "Cabeza olmeca. La cultura madre todavía te mira.",
    city: "Tabasco",
    image: "/clips/olmec.jpg",
    likes: 0,
    comments: [],
    tags: ["olmeca", "parati"],
    sound: "Rostro de basalto",
    soundArtist: "Otealo",
  },
  {
    id: "tula",
    user: "otealo",
    displayName: "Otealo",
    caption: "Atlantes de Tula. Los toltecas no se sentaron.",
    city: "Hidalgo",
    image: "/clips/tula.jpg",
    likes: 0,
    comments: [],
    tags: ["tolteca", "tula", "parati"],
    sound: "Guerreros de piedra",
    soundArtist: "Otealo",
  },
  {
    id: "mitla",
    user: "otealo",
    displayName: "Otealo",
    caption: "Mitla. Grecas que no se cansan de repetir el cielo.",
    city: "Oaxaca",
    image: "/clips/mitla.jpg",
    likes: 0,
    comments: [],
    tags: ["zapoteca", "mitla", "parati"],
    sound: "Mosaico eterno",
    soundArtist: "Otealo",
  },
  {
    id: "lunapir",
    user: "otealo",
    displayName: "Otealo",
    caption: "Pirámide de la Luna. La calzada apunta al volcán.",
    city: "Estado de México",
    image: "/clips/lunapir.jpg",
    likes: 0,
    comments: [],
    tags: ["teotihuacan", "piramide", "parati"],
    sound: "Avenida de los Muertos",
    soundArtist: "Otealo",
  },
  {
    id: "palacio",
    user: "otealo",
    displayName: "Otealo",
    caption: "Palacio de Palenque. Aquí vivió Pakal, no un mito.",
    city: "Chiapas",
    image: "/clips/palacio.jpg",
    likes: 0,
    comments: [],
    tags: ["maya", "palenque", "parati"],
    sound: "Torre de niebla",
    soundArtist: "Otealo",
  },
  {
    id: "yaxchilan",
    user: "otealo",
    displayName: "Otealo",
    caption: "Yaxchilán. El río Usumacinta guarda los dinteles.",
    city: "Chiapas",
    image: "/clips/yaxchilan.jpg",
    likes: 0,
    comments: [],
    tags: ["maya", "yaxchilan", "parati"],
    sound: "Templo del río",
    soundArtist: "Otealo",
  },
  {
    id: "chichennoche",
    user: "otealo",
    displayName: "Otealo",
    caption: "Chichén de noche. El Castillo no duerme.",
    city: "Yucatán",
    image: "/clips/chichennoche.jpg",
    likes: 0,
    comments: [],
    tags: ["maya", "chichen", "parati"],
    sound: "Pirámide encendida",
    soundArtist: "Otealo",
  },
  {
    id: "piedrasol",
    user: "otealo",
    displayName: "Otealo",
    caption: "Piedra del Sol. El calendario mexica sigue girando.",
    city: "Ciudad de México",
    image: "/clips/piedrasol.jpg",
    likes: 0,
    comments: [],
    tags: ["azteca", "mexica", "parati"],
    sound: "Disco de basalto",
    soundArtist: "Otealo",
  },
  {
    id: "milpa",
    user: "otealo",
    displayName: "Otealo",
    caption: "La milpa. Maíz, frijol y calabaza: el primer México.",
    city: "Puebla",
    image: "/clips/milpa.jpg",
    likes: 0,
    comments: [],
    tags: ["milpa", "cultura", "parati"],
    sound: "Tres hermanas",
    soundArtist: "Otealo",
  },
  {
    id: "olmecplaza",
    user: "otealo",
    displayName: "Otealo",
    caption: "Olmeca. La cultura madre ya tenía ciudad.",
    city: "Tabasco",
    image: "/clips/olmecplaza.jpg",
    likes: 0,
    comments: [],
    tags: ["olmeca", "parati"],
    sound: "Plaza de cabezas",
    soundArtist: "Otealo",
  },
  {
    id: "chinampa",
    user: "otealo",
    displayName: "Otealo",
    caption: "Chinampa. Tenochtitlan todavía flota en Xochimilco.",
    city: "Ciudad de México",
    image: "/clips/chinampa.jpg",
    likes: 0,
    comments: [],
    tags: ["mexica", "chinampa", "parati"],
    sound: "Jardín en el agua",
    soundArtist: "Otealo",
  },
  {
    id: "retablo",
    user: "otealo",
    displayName: "Otealo",
    caption: "Oro e indígenas en el retablo. Así nació lo mestizo.",
    city: "Puebla",
    image: "/clips/retablo.jpg",
    likes: 0,
    comments: [],
    tags: ["colonial", "mestizo", "parati"],
    sound: "Barroco mexicano",
    soundArtist: "Otealo",
  },
  {
    id: "dolores",
    user: "otealo",
    displayName: "Otealo",
    caption: "Dolores Hidalgo. Aquí empezó el Grito.",
    city: "Guanajuato",
    image: "/clips/dolores.jpg",
    likes: 0,
    comments: [],
    tags: ["independencia", "parati"],
    sound: "Campana de Dolores",
    soundArtist: "Otealo",
  },
  {
    id: "revolucion",
    user: "otealo",
    displayName: "Otealo",
    caption: "Revolución. Tierra y libertad no fueron un lema vacío.",
    city: "Morelos",
    image: "/clips/revolucion.jpg",
    likes: 0,
    comments: [],
    tags: ["revolucion", "parati"],
    sound: "Camino de soldaderas",
    soundArtist: "Otealo",
  },
  {
    id: "mural",
    user: "otealo",
    displayName: "Otealo",
    caption: "El mural cuenta lo que los libros callaban.",
    city: "Ciudad de México",
    image: "/clips/mural.jpg",
    likes: 0,
    comments: [],
    tags: ["muralismo", "parati"],
    sound: "Historia en fresco",
    soundArtist: "Otealo",
  },
  {
    id: "ofrenda",
    user: "otealo",
    displayName: "Otealo",
    caption: "Ofrenda. Los muertos vuelven si les pones flor y pan.",
    city: "Michoacán",
    image: "/clips/ofrenda.jpg",
    likes: 0,
    comments: [],
    tags: ["muertos", "parati"],
    sound: "Cempasúchil",
    soundArtist: "Otealo",
  },
  {
    id: "cacao",
    user: "otealo",
    displayName: "Otealo",
    caption: "Cacao en metate. El chocolate nació aquí, no en Suiza.",
    city: "Tabasco",
    image: "/clips/cacao.jpg",
    likes: 0,
    comments: [],
    tags: ["cacao", "comida", "parati"],
    sound: "Grano sagrado",
    soundArtist: "Otealo",
  },
  {
    id: "jarocho",
    user: "otealo",
    displayName: "Otealo",
    caption: "Son jarocho. África, indio y España en una tarima.",
    city: "Veracruz",
    image: "/clips/jarocho.jpg",
    likes: 0,
    comments: [],
    tags: ["jarocho", "musica", "parati"],
    sound: "Zapateado del puerto",
    soundArtist: "Otealo",
  },
  {
    id: "telar",
    user: "otealo",
    displayName: "Otealo",
    caption: "Telar de cintura. El hilo también es idioma.",
    city: "Oaxaca",
    image: "/clips/telar.jpg",
    likes: 0,
    comments: [],
    tags: ["textil", "indigena", "parati"],
    sound: "Hilo de pueblo",
    soundArtist: "Otealo",
  },
  {
    id: "fiesta",
    user: "otealo",
    displayName: "Otealo",
    caption: "Fiesta patronal. El santo, el pueblo y los cohetes.",
    city: "Oaxaca",
    image: "/clips/fiesta.jpg",
    likes: 0,
    comments: [],
    tags: ["fiesta", "parati"],
    sound: "Castillo de feria",
    soundArtist: "Otealo",
  },
];

const CITY_HANDLE: Record<string, { user: string; displayName: string }> = {
  "Ciudad de México": { user: "centro.cdmx", displayName: "Centro CDMX" },
  Guadalajara: { user: "guadalajara.nights", displayName: "GDL Nights" },
  Monterrey: { user: "norteno.mx", displayName: "Norteño" },
  Mérida: { user: "yucatan.sabor", displayName: "Yucatán Sabor" },
  Cancún: { user: "caribe.ojo", displayName: "Caribe Ojo" },
  Oaxaca: { user: "istmo.luz", displayName: "Istmo Luz" },
  Puebla: { user: "puebla.mole", displayName: "Puebla Mole" },
  Tijuana: { user: "norteno.mx", displayName: "Norteño" },
  León: { user: "guadalajara.nights", displayName: "GDL Nights" },
  Querétaro: { user: "centro.cdmx", displayName: "Centro CDMX" },
  Guanajuato: { user: "campana.gto", displayName: "Campana GTO" },
  Morelos: { user: "piedra.antigua", displayName: "Piedra Antigua" },
  Michoacán: { user: "istmo.luz", displayName: "Istmo Luz" },
  Madrid: { user: "iberia.ojo", displayName: "Iberia Ojo" },
  Sevilla: { user: "iberia.ojo", displayName: "Iberia Ojo" },
  Granada: { user: "iberia.ojo", displayName: "Iberia Ojo" },
  Barcelona: { user: "iberia.ojo", displayName: "Iberia Ojo" },
  Buñol: { user: "iberia.ojo", displayName: "Iberia Ojo" },
  "Santiago de Compostela": { user: "iberia.ojo", displayName: "Iberia Ojo" },
};

export function stampHouseCreator<
  T extends { user: string; displayName: string; city?: string; country?: ClipCountry },
>(clip: T): T {
  if (clip.user && clip.user !== "otealo") return clip;
  if (clip.country === "ES") {
    return { ...clip, user: "iberia.ojo", displayName: "Iberia Ojo" };
  }
  const hit = CITY_HANDLE[clip.city ?? ""];
  return hit ? { ...clip, user: hit.user, displayName: hit.displayName } : clip;
}

export const SEED_CLIPS: Clip[] = [...RAW_CLIPS, ...EDITORIAL_CLIPS, ...CALENDAR_CLIPS].map((c) => {
  const country = inferCountry(c);
  const stamped = stampHouseCreator({ ...c, country });
  return {
    ...stamped,
    likes: 0,
    comments: [],
    shares: 0,
    live: false,
    viewers: undefined,
    following: false,
    friend: false,
    video: c.video ?? seedClipVideoUrl(c.id),
    series: inferSeries(c),
    country,
  };
});

export function mergeClipFeeds(...lists: Clip[][]) {
  const seen = new Set<string>();
  const out: Clip[] = [];
  for (const list of lists) {
    for (const clip of list) {
      if (!clip?.id || seen.has(clip.id)) continue;
      seen.add(clip.id);
      out.push(clip);
    }
  }
  return out;
}

export function shuffleClips(clips: Clip[]) {
  const out = [...clips];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const a = out[i]!;
    const b = out[j]!;
    out[i] = b;
    out[j] = a;
  }
  return out;
}

/** Keep current order. Drop gone clips. Insert new ones at random spots. */
export function mergeIntoShuffled(current: Clip[], incoming: Clip[]) {
  const next = new Map(incoming.filter((c) => c?.id).map((c) => [c.id, c]));
  const kept: Clip[] = [];
  for (const clip of current) {
    const fresh = next.get(clip.id);
    if (!fresh) continue;
    kept.push({ ...clip, ...fresh, comments: fresh.comments?.length ? fresh.comments : clip.comments });
    next.delete(clip.id);
  }
  const extras = [...next.values()];
  const out = [...kept];
  for (const clip of extras) {
    const i = Math.floor(Math.random() * (out.length + 1));
    out.splice(i, 0, clip);
  }
  return out;
}

export const FRIEND_USERS = [
  ...new Set(SEED_CLIPS.filter((c) => c.friend).map((c) => c.user)),
];

export const EXPLORE_TAGS = [...region.seedTags];

export const CITIES = [...region.cities];

export const STORIES = [
  { user: "chile_y_lima", label: "Tacos", image: "/clips/tacos.jpg" },
  { user: "centro.cdmx", label: "CDMX", image: "/clips/zocalo.jpg" },
  { user: "istmo.luz", label: "Oaxaca", image: "/clips/oaxaca.jpg" },
  { user: "piedra.antigua", label: "Mayas", image: "/clips/chichen.jpg" },
  { user: "caribe.ojo", label: "Caribe", image: "/clips/playa.jpg" },
  { user: "guadalajara.nights", label: "GDL", image: "/clips/gdl.jpg" },
  { user: "arena.mexico", label: "Lucha", image: "/clips/lucha.jpg" },
  { user: "norteno.mx", label: "Norte", image: "/clips/monterrey.jpg" },
];

export const SEED_NOTES: Array<{
  id: string;
  text: string;
  time: string;
  unread: boolean;
  kind: "feed" | "user" | "sound";
  user?: string;
  sound?: string;
}> = [];
