import { seedClipVideoUrl } from "./media";
import { region } from "./region";

export type Comment = { user: string; text: string };

export type Clip = {
  id: string;
  user: string;
  displayName: string;
  caption: string;
  city: string;
  image: string;
  video?: string;
  likes: number;
  comments: Comment[];
  tags: string[];
  sound: string;
  soundArtist: string;
  following?: boolean;
  live?: boolean;
  viewers?: number;
  shares?: number;
  friend?: boolean;
};

const RAW_CLIPS: Clip[] = [
  {
    id: "tacos",
    user: "chile_y_lima",
    displayName: "Chile y Lima",
    caption: "Pastor a las 2am en la Roma. Si no hay piña, no es pastor.",
    city: "Ciudad de México",
    image: "/clips/tacos.jpg",
    likes: 12400,
    comments: [
      { user: "taquero.sur", text: "¿Cuál taquería?" },
      { user: "hambre.mx", text: "Se me antojó feo" },
      { user: "roma.norte", text: "Roma best colonia" },
    ],
    tags: ["tacos", "CDMX", "parati"],
    sound: "Pastor a las 2",
    soundArtist: "Sonido Roma",
  },
  {
    id: "trompo",
    user: "chile_y_lima",
    displayName: "Chile y Lima",
    caption: "El trompo no miente. Naranja, piña, y la fila que da la vuelta.",
    city: "Ciudad de México",
    image: "/clips/trompo.jpg",
    likes: 18900,
    comments: [{ user: "noche.cdmx", text: "Esa luz es de iglesia" }],
    tags: ["tacos", "CDMX", "comida"],
    sound: "Trompo mix",
    soundArtist: "Sonido Roma",
    live: true,
    viewers: 1840,
  },
  {
    id: "gdl",
    user: "guadalajara.nights",
    displayName: "GDL Nights",
    caption: "Papel picado, calle viva. Jalisco no es México — es otra cosa.",
    city: "Guadalajara",
    image: "/clips/gdl.jpg",
    likes: 8100,
    comments: [
      { user: "tapatia", text: "Jalisco es México" },
      { user: "centro.gdl", text: "¿En qué calle?" },
    ],
    tags: ["Guadalajara", "parati"],
    sound: "Calle viva",
    soundArtist: "Banda Jalisco",
    following: true,
  },
  {
    id: "monterrey",
    user: "norteno.mx",
    displayName: "Norteño",
    caption: "El Cerro de la Silla no pide permiso. Siempre está.",
    city: "Monterrey",
    image: "/clips/monterrey.jpg",
    likes: 6700,
    comments: [{ user: "mty.pride", text: "Orgullo regiomontano" }],
    tags: ["Monterrey", "MTY"],
    sound: "Banda del Cerro",
    soundArtist: "Norteño MX",
    following: true,
  },
  {
    id: "merida",
    user: "yucatan.sabor",
    displayName: "Yucatán Sabor",
    caption: "Arco de San Juan. Cochinita después, si aguantas el calor.",
    city: "Mérida",
    image: "/clips/merida.jpg",
    likes: 9900,
    comments: [{ user: "peninsula", text: "Con cebolla morada o nada" }],
    tags: ["Merida", "Yucatan"],
    sound: "Trova de mediodía",
    soundArtist: "Yucatán Sabor",
  },
  {
    id: "zocalo",
    user: "centro.cdmx",
    displayName: "Centro CDMX",
    caption: "Catedral de noche. El Zócalo nunca duerme del todo.",
    city: "Ciudad de México",
    image: "/clips/zocalo.jpg",
    likes: 15200,
    comments: [{ user: "noctambulo", text: "Esa luz pega distinto" }],
    tags: ["CDMX", "zocalo"],
    sound: "Cumbia del Zócalo",
    soundArtist: "Centro CDMX",
    live: true,
    viewers: 920,
  },
  {
    id: "playa",
    user: "caribe.ojo",
    displayName: "Caribe Ojo",
    caption: "El Caribe no es filtro. Es así.",
    city: "Quintana Roo",
    image: "/clips/playa.jpg",
    likes: 22100,
    comments: [{ user: "playa.fan", text: "Ya quiero ir" }],
    tags: ["playa", "caribe"],
    sound: "Dembow Caribe",
    soundArtist: "Caribe Ojo",
  },
  {
    id: "cancun",
    user: "zona.hotelera",
    displayName: "Zona Hotelera",
    caption: "Cancún desde arriba. Turquesa de verdad.",
    city: "Cancún",
    image: "/clips/cancun.jpg",
    likes: 18800,
    comments: [{ user: "qroo", text: "Clásico" }],
    tags: ["Cancun", "playa"],
    sound: "House Hotelera",
    soundArtist: "Zona Hotelera",
    following: true,
  },
  {
    id: "puebla",
    user: "puebla.mole",
    displayName: "Puebla Mole",
    caption: "Mole que sí sabe a casa. Puebla no perdona mediocre.",
    city: "Puebla",
    image: "/clips/puebla.jpg",
    likes: 5400,
    comments: [{ user: "angelopolis", text: "Con arroz, por favor" }],
    tags: ["Puebla", "comida"],
    sound: "Son de Puebla",
    soundArtist: "Puebla Mole",
  },
  {
    id: "mercado",
    user: "tianguis.vivo",
    displayName: "Tianguis Vivo",
    caption: "Textiles, sol, cobblestone. El tianguis manda.",
    city: "Puebla",
    image: "/clips/mercado.jpg",
    likes: 4300,
    comments: [{ user: "artesana", text: "Me llevo el rebozo" }],
    tags: ["mercado", "Puebla"],
    sound: "Huapango tianguis",
    soundArtist: "Tianguis Vivo",
  },
  {
    id: "lucha",
    user: "arena.mexico",
    displayName: "Arena México",
    caption: "Tercera caída. Si no gritas, no estabas.",
    city: "Ciudad de México",
    image: "/clips/lucha.jpg",
    likes: 30100,
    comments: [
      { user: "rudo.oficial", text: "Esa máscara es leyenda" },
      { user: "tecnico", text: "Tercera caída siempre" },
    ],
    tags: ["lucha", "CDMX", "parati"],
    sound: "Campana de arena",
    soundArtist: "Arena México",
    live: true,
    viewers: 4120,
  },
  {
    id: "tulum",
    user: "caribe.ojo",
    displayName: "Caribe Ojo",
    caption: "Tulum sin influencer. Solo piedra, mar y el sol que pega.",
    city: "Tulum",
    image: "/clips/tulum.jpg",
    likes: 27400,
    comments: [{ user: "mayan.coast", text: "Esto sí es Quintana Roo" }],
    tags: ["playa", "Tulum", "caribe"],
    sound: "Selva Tulum",
    soundArtist: "Caribe Ojo",
  },
  {
    id: "oaxaca",
    user: "istmo.luz",
    displayName: "Istmo Luz",
    caption: "Oaxaca al atardecer. El papel picado ya es parte del cielo.",
    city: "Oaxaca",
    image: "/clips/oaxaca.jpg",
    likes: 14200,
    comments: [{ user: "mezcal.claro", text: "¿En Santo Domingo?" }],
    tags: ["Oaxaca", "parati"],
    sound: "Son istmeño",
    soundArtist: "Istmo Luz",
    following: true,
  },
  {
    id: "bellas",
    user: "centro.cdmx",
    displayName: "Centro CDMX",
    caption: "Bellas Artes después de la lluvia. El mármol se ve de oro.",
    city: "Ciudad de México",
    image: "/clips/bellas.jpg",
    likes: 19800,
    comments: [{ user: "cultura.mx", text: "Esta ciudad no se acaba" }],
    tags: ["CDMX", "cultura"],
    sound: "Nocturno Bellas Artes",
    soundArtist: "Centro CDMX",
  },
  {
    id: "alebrijes",
    user: "tianguis.vivo",
    displayName: "Tianguis Vivo",
    caption: "Alebrijes que te miran de vuelta. Hecho a mano, no de souvenir.",
    city: "Oaxaca",
    image: "/clips/alebrijes.jpg",
    likes: 8700,
    comments: [{ user: "taller.oax", text: "Ese jaguar está vivo" }],
    tags: ["Oaxaca", "mercado", "arte"],
    sound: "Alebrije beat",
    soundArtist: "Tianguis Vivo",
  },
];

const EDITORIAL_CLIPS: Clip[] = [
  {
    id: "pastor2",
    user: "otealo",
    displayName: "Otealo",
    caption: "Pastor que no duerme. Roma Norte, 1am.",
    city: "Ciudad de México",
    image: "/clips/pastor2.jpg",
    likes: 0,
    comments: [],
    tags: ["tacos", "CDMX", "parati"],
    sound: "Trompo de noche",
    soundArtist: "Otealo",
  },
  {
    id: "mariachi",
    user: "otealo",
    displayName: "Otealo",
    caption: "El Grito no pide permiso. Plaza y trompeta.",
    city: "Guadalajara",
    image: "/clips/mariachi.jpg",
    likes: 0,
    comments: [],
    tags: ["musica", "mariachi", "parati"],
    sound: "Son de plaza",
    soundArtist: "Otealo",
  },
  {
    id: "caribe",
    user: "otealo",
    displayName: "Otealo",
    caption: "El Caribe no es filtro. Es así.",
    city: "Cancún",
    image: "/clips/caribe.jpg",
    likes: 0,
    comments: [],
    tags: ["playa", "caribe", "parati"],
    sound: "Ola turquesa",
    soundArtist: "Otealo",
  },
  {
    id: "lucha2",
    user: "otealo",
    displayName: "Otealo",
    caption: "Máscara, tercera caída, la gente de pie.",
    city: "Ciudad de México",
    image: "/clips/lucha2.jpg",
    likes: 0,
    comments: [],
    tags: ["lucha", "CDMX", "parati"],
    sound: "Campana arena",
    soundArtist: "Otealo",
  },
  {
    id: "mercado2",
    user: "otealo",
    displayName: "Otealo",
    caption: "Mole, cempasúchil y alebrijes que te miran.",
    city: "Oaxaca",
    image: "/clips/mercado2.jpg",
    likes: 0,
    comments: [],
    tags: ["mercado", "oaxaca", "parati"],
    sound: "Tianguis vivo",
    soundArtist: "Otealo",
  },
  {
    id: "zocalo2",
    user: "otealo",
    displayName: "Otealo",
    caption: "La Catedral se enciende y el Zócalo sigue.",
    city: "Ciudad de México",
    image: "/clips/zocalo2.jpg",
    likes: 0,
    comments: [],
    tags: ["CDMX", "zocalo", "parati"],
    sound: "Campanas de noche",
    soundArtist: "Otealo",
  },
  {
    id: "gdl2",
    user: "otealo",
    displayName: "Otealo",
    caption: "Guadalajara de noche. La plaza no se acaba.",
    city: "Guadalajara",
    image: "/clips/gdl2.jpg",
    likes: 0,
    comments: [],
    tags: ["guadalajara", "parati"],
    sound: "Tapatía",
    soundArtist: "Otealo",
  },
  {
    id: "chichen",
    user: "otealo",
    displayName: "Otealo",
    caption: "Kukulcán no necesita filtro.",
    city: "Yucatán",
    image: "/clips/chichen.jpg",
    likes: 0,
    comments: [],
    tags: ["yucatan", "parati"],
    sound: "Sol maya",
    soundArtist: "Otealo",
  },
  {
    id: "paletas",
    user: "otealo",
    displayName: "Otealo",
    caption: "Paleta, sol, y la playa al fondo.",
    city: "Quintana Roo",
    image: "/clips/paletas.jpg",
    likes: 0,
    comments: [],
    tags: ["playa", "parati"],
    sound: "Carrito dulce",
    soundArtist: "Otealo",
  },
  {
    id: "metro",
    user: "otealo",
    displayName: "Otealo",
    caption: "Insurgentes. Naranja, prisa, México.",
    city: "Ciudad de México",
    image: "/clips/metro.jpg",
    likes: 0,
    comments: [],
    tags: ["CDMX", "metro", "parati"],
    sound: "Andén naranja",
    soundArtist: "Otealo",
  },
  {
    id: "sanmiguel",
    user: "otealo",
    displayName: "Otealo",
    caption: "Lluvia en adoquín. San Miguel se ve de oro.",
    city: "Guanajuato",
    image: "/clips/sanmiguel.jpg",
    likes: 0,
    comments: [],
    tags: ["sanmiguel", "parati"],
    sound: "Lluvia colonial",
    soundArtist: "Otealo",
  },
  {
    id: "futbol",
    user: "otealo",
    displayName: "Otealo",
    caption: "La afición es el onceavo.",
    city: "Ciudad de México",
    image: "/clips/futbol.jpg",
    likes: 0,
    comments: [],
    tags: ["futbol", "parati"],
    sound: "Cántico verde",
    soundArtist: "Otealo",
  },
  {
    id: "xochi",
    user: "otealo",
    displayName: "Otealo",
    caption: "Trajinera, cempasúchil, y el canal que no se acaba.",
    city: "Ciudad de México",
    image: "/clips/xochi.jpg",
    likes: 0,
    comments: [],
    tags: ["xochimilco", "CDMX", "parati"],
    sound: "Canal de flores",
    soundArtist: "Otealo",
  },
  {
    id: "teoti",
    user: "otealo",
    displayName: "Otealo",
    caption: "Calzada de los Muertos. El sol pega distinto.",
    city: "Estado de México",
    image: "/clips/teoti.jpg",
    likes: 0,
    comments: [],
    tags: ["teotihuacan", "parati"],
    sound: "Sol de pirámide",
    soundArtist: "Otealo",
  },
  {
    id: "coyoacan",
    user: "otealo",
    displayName: "Otealo",
    caption: "Coyoacán de jacaranda. La calle es el filtro.",
    city: "Ciudad de México",
    image: "/clips/coyoacan.jpg",
    likes: 0,
    comments: [],
    tags: ["coyoacan", "CDMX", "parati"],
    sound: "Bici en cobble",
    soundArtist: "Otealo",
  },
  {
    id: "mezcal",
    user: "otealo",
    displayName: "Otealo",
    caption: "Mezcal que huele a pueblo. Copita y ya.",
    city: "Oaxaca",
    image: "/clips/mezcal.jpg",
    likes: 0,
    comments: [],
    tags: ["mezcal", "oaxaca", "parati"],
    sound: "Copita humeante",
    soundArtist: "Otealo",
  },
  {
    id: "cabo",
    user: "otealo",
    displayName: "Otealo",
    caption: "El Arco no se cansa de pelear con el mar.",
    city: "Los Cabos",
    image: "/clips/cabo.jpg",
    likes: 0,
    comments: [],
    tags: ["cabo", "playa", "parati"],
    sound: "Rompeolas",
    soundArtist: "Otealo",
  },
  {
    id: "chapu",
    user: "otealo",
    displayName: "Otealo",
    caption: "Chapultepec en lancha. Fin de semana mexicano.",
    city: "Ciudad de México",
    image: "/clips/chapu.jpg",
    likes: 0,
    comments: [],
    tags: ["chapultepec", "CDMX", "parati"],
    sound: "Lago del bosque",
    soundArtist: "Otealo",
  },
  {
    id: "tamales",
    user: "otealo",
    displayName: "Otealo",
    caption: "Tamales a las 7am. El vapor no miente.",
    city: "Ciudad de México",
    image: "/clips/tamales.jpg",
    likes: 0,
    comments: [],
    tags: ["tamales", "CDMX", "parati"],
    sound: "Olla de vapor",
    soundArtist: "Otealo",
  },
  {
    id: "folklor",
    user: "otealo",
    displayName: "Otealo",
    caption: "La falda da la vuelta y Jalisco aplaude.",
    city: "Guadalajara",
    image: "/clips/folklor.jpg",
    likes: 0,
    comments: [],
    tags: ["folklor", "jalisco", "parati"],
    sound: "Zapateado",
    soundArtist: "Otealo",
  },
  {
    id: "cenote",
    user: "otealo",
    displayName: "Otealo",
    caption: "Cenote. El sol entra por un hueco y ya es iglesia.",
    city: "Yucatán",
    image: "/clips/cenote.jpg",
    likes: 0,
    comments: [],
    tags: ["cenote", "yucatan", "parati"],
    sound: "Agua sagrada",
    soundArtist: "Otealo",
  },
  {
    id: "agave",
    user: "otealo",
    displayName: "Otealo",
    caption: "Agave hasta el volcán. Jalisco de verdad.",
    city: "Jalisco",
    image: "/clips/agave.jpg",
    likes: 0,
    comments: [],
    tags: ["tequila", "jalisco", "parati"],
    sound: "Campo azul",
    soundArtist: "Otealo",
  },
  {
    id: "vallarta",
    user: "otealo",
    displayName: "Otealo",
    caption: "Malecón de Vallarta. El sol se rinde despacio.",
    city: "Puerto Vallarta",
    image: "/clips/vallarta.jpg",
    likes: 0,
    comments: [],
    tags: ["vallarta", "playa", "parati"],
    sound: "Atardecer malecón",
    soundArtist: "Otealo",
  },
  {
    id: "taxco",
    user: "otealo",
    displayName: "Otealo",
    caption: "Taxco se cuelga de la montaña. Plata y campanas.",
    city: "Guerrero",
    image: "/clips/taxco.jpg",
    likes: 0,
    comments: [],
    tags: ["taxco", "parati"],
    sound: "Cerro de plata",
    soundArtist: "Otealo",
  },
];

export const SEED_CLIPS: Clip[] = [...RAW_CLIPS, ...EDITORIAL_CLIPS].map((c) => ({
  ...c,
  user: "otealo",
  displayName: "Otealo",
  likes: 0,
  comments: [],
  shares: 0,
  live: false,
  viewers: undefined,
  following: false,
  friend: false,
  video: c.video ?? seedClipVideoUrl(c.id),
}));

export function mergeClipFeeds(...lists: Clip[][]) {
  const seen = new Set<string>();
  const out: Clip[] = [];
  for (const list of lists) {
    for (const clip of list) {
      if (!clip?.id || seen.has(clip.id)) continue;
      seen.add(clip.id);
      out.push(clip);
    }
  }
  return out;
}

export const FRIEND_USERS = [
  ...new Set(SEED_CLIPS.filter((c) => c.friend).map((c) => c.user)),
];

export const EXPLORE_TAGS = [...region.seedTags];

export const CITIES = [...region.cities];

export const STORIES = [
  { user: "otealo", image: "/clips/xochi.jpg" },
  { user: "otealo", image: "/clips/cenote.jpg" },
  { user: "otealo", image: "/clips/mariachi.jpg" },
  { user: "otealo", image: "/clips/cabo.jpg" },
  { user: "otealo", image: "/clips/folklor.jpg" },
  { user: "otealo", image: "/clips/mezcal.jpg" },
  { user: "otealo", image: "/clips/taxco.jpg" },
];

export const SEED_NOTES: Array<{
  id: string;
  text: string;
  time: string;
  unread: boolean;
  kind: "feed" | "user" | "sound";
  user?: string;
  sound?: string;
}> = [];
