import type { Clip } from "./clips";

/** TikTok street clips, credited to the original account. Not @otealo. */
export const TIK_CLIPS: Clip[] = [
  {
    id: "tk-r01",
    user: "tolucastreetfood",
    displayName: "Toluca Street Food",
    caption: "Tacos al pastor en CDMX. Vía @tolucastreetfood",
    city: "Ciudad de México",
    image: "/clips/tk-r01.jpg",
    video: "/clips/tk-r01.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "tolucastreetfood",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r02",
    user: "viajeropeligro",
    displayName: "Viajero Peligro",
    caption: "El Vilsito, Narvarte: el taller con los pastor que sí. Vía @viajeropeligro",
    city: "Ciudad de México",
    image: "/clips/tk-r02.jpg",
    video: "/clips/tk-r02.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "Narvarte", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "viajeropeligro",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r03",
    user: "liliana_lago",
    displayName: "Liliana Lago Food",
    caption: "Trompo de 300 kilos. El pastor no cabe en la foto. Vía @liliana_lago",
    city: "Ciudad de México",
    image: "/clips/tk-r03.jpg",
    video: "/clips/tk-r03.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "trompo", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "liliana_lago",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r04",
    user: "mxico.de.mi.coraz",
    displayName: "México de mi Corazón",
    caption: "Tacos al pastor, CDMX. Vía @mxico.de.mi.coraz",
    city: "Ciudad de México",
    image: "/clips/tk-r04.jpg",
    video: "/clips/tk-r04.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "mxico.de.mi.coraz",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r05",
    user: "carrilmore",
    displayName: "More Carry",
    caption: "Pastor en la calle. CDMX. Vía @carrilmore",
    city: "Ciudad de México",
    image: "/clips/tk-r05.jpg",
    video: "/clips/tk-r05.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "carrilmore",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r06",
    user: "plantacos.cdmx",
    displayName: "Plantacos CDMX",
    caption: "Puesto en Guanajuato 53, Roma Norte. Vía @plantacos.cdmx",
    city: "Ciudad de México",
    image: "/clips/tk-r06.jpg",
    video: "/clips/tk-r06.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "Roma", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "plantacos.cdmx",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r07",
    user: "la_que_vuela",
    displayName: "Jocelyn Aguilar",
    caption: "No Suaperro, Zacatecas 229, Roma Norte. Vía @la_que_vuela",
    city: "Ciudad de México",
    image: "/clips/tk-r07.jpg",
    video: "/clips/tk-r07.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "Roma", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "la_que_vuela",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r08",
    user: "taqueriareforma2021",
    displayName: "Reforma Taquería",
    caption: "Tacos al pastor, Taquería Reforma. Vía @taqueriareforma2021",
    city: "Ciudad de México",
    image: "/clips/tk-r08.jpg",
    video: "/clips/tk-r08.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "taqueriareforma2021",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r09",
    user: "diegormz49",
    displayName: "diegormz49",
    caption: "Pastor en Reforma, periferia oriente. Vía @diegormz49",
    city: "Ciudad de México",
    image: "/clips/tk-r09.jpg",
    video: "/clips/tk-r09.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "diegormz49",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r10",
    user: "vasotequedas",
    displayName: "¿Vas o te quedas?",
    caption: "Tacos en la Roma. Vía @vasotequedas",
    city: "Ciudad de México",
    image: "/clips/tk-r10.jpg",
    video: "/clips/tk-r10.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "Roma", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "vasotequedas",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r11",
    user: "fernandorosario110",
    displayName: "Fernando Rosario",
    caption: "Esquites en la Ciudad de México. Vía @fernandorosario110",
    city: "Ciudad de México",
    image: "/clips/tk-r11.jpg",
    video: "/clips/tk-r11.mp4",
    likes: 0,
    comments: [],
    tags: ["elote", "esquites", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "fernandorosario110",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r12",
    user: "johana_chavez19",
    displayName: "Johana Chávez",
    caption: "Organillero en el Zócalo. Vía @johana_chavez19",
    city: "Ciudad de México",
    image: "/clips/tk-r12.jpg",
    video: "/clips/tk-r12.mp4",
    likes: 0,
    comments: [],
    tags: ["organillo", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "johana_chavez19",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r13",
    user: "vicestrellaa",
    displayName: "Vic Estrella",
    caption: "El organillero. Personaje de la ciudad. Vía @vicestrellaa",
    city: "Ciudad de México",
    image: "/clips/tk-r13.jpg",
    video: "/clips/tk-r13.mp4",
    likes: 0,
    comments: [],
    tags: ["organillo", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "vicestrellaa",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r14",
    user: "fernandaadamel",
    displayName: "Fer Adame",
    caption: "Plaza Garibaldi. El mariachi no pide cita. Vía @fernandaadamel",
    city: "Ciudad de México",
    image: "/clips/tk-r14.jpg",
    video: "/clips/tk-r14.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "Garibaldi", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "fernandaadamel",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r15",
    user: "yolore_",
    displayName: "Lore",
    caption: "Arena México. Si estás en CDMX, una función. Vía @yolore_",
    city: "Ciudad de México",
    image: "/clips/tk-r15.jpg",
    video: "/clips/tk-r15.mp4",
    likes: 0,
    comments: [],
    tags: ["lucha", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "yolore_",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r16",
    user: "tatianago_",
    displayName: "Tatiana",
    caption: "Teotihuacán. México y sus maravillas. Vía @tatianago_",
    city: "Ciudad de México",
    image: "/clips/tk-r16.jpg",
    video: "/clips/tk-r16.mp4",
    likes: 0,
    comments: [],
    tags: ["teotihuacan", "piramide", "historia", "parati"],
    sound: "Sonido original",
    soundArtist: "tatianago_",
    series: "HistorySnack",
    country: "MX",
  },
  {
    id: "tk-r17",
    user: "luz.irai",
    displayName: "Irai",
    caption: "Las pirámides de Teotihuacán. Cansado, valió. Vía @luz.irai",
    city: "Ciudad de México",
    image: "/clips/tk-r17.jpg",
    video: "/clips/tk-r17.mp4",
    likes: 0,
    comments: [],
    tags: ["teotihuacan", "piramide", "historia", "parati"],
    sound: "Sonido original",
    soundArtist: "luz.irai",
    series: "HistorySnack",
    country: "MX",
  },
  {
    id: "tk-r18",
    user: "oaxacacultural",
    displayName: "Oaxaca Cultural",
    caption: "Artesanías en el Mercado de Abastos, Oaxaca. Vía @oaxacacultural",
    city: "Oaxaca",
    image: "/clips/tk-r18.jpg",
    video: "/clips/tk-r18.mp4",
    likes: 0,
    comments: [],
    tags: ["oaxaca", "mercado", "parati"],
    sound: "Sonido original",
    soundArtist: "oaxacacultural",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r19",
    user: "clubtengohambre",
    displayName: "Club Tengo Hambre",
    caption: "Chapulines en la Central de Abastos, Oaxaca. Vía @clubtengohambre",
    city: "Oaxaca",
    image: "/clips/tk-r19.jpg",
    video: "/clips/tk-r19.mp4",
    likes: 0,
    comments: [],
    tags: ["oaxaca", "mercado", "parati"],
    sound: "Sonido original",
    soundArtist: "clubtengohambre",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r20",
    user: "noemiruiz_4",
    displayName: "Noemi Ruiz",
    caption: "Tamales oaxaqueños. Amarillo de pollo. Vía @noemiruiz_4",
    city: "Oaxaca",
    image: "/clips/tk-r20.jpg",
    video: "/clips/tk-r20.mp4",
    likes: 0,
    comments: [],
    tags: ["tamales", "oaxaca", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "noemiruiz_4",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r21",
    user: "mellamansabina",
    displayName: "Mellamansabina",
    caption: "No solo comí tamales: me enseñaron a hacerlos. Vía @mellamansabina",
    city: "Oaxaca",
    image: "/clips/tk-r21.jpg",
    video: "/clips/tk-r21.mp4",
    likes: 0,
    comments: [],
    tags: ["tamales", "oaxaca", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "mellamansabina",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r22",
    user: "el.rincon.del.postre",
    displayName: "El rincón del postre",
    caption: "Pozole para las fiestas. Ajúa. Vía @el.rincon.del.postre",
    city: "Guadalajara",
    image: "/clips/tk-r22.jpg",
    video: "/clips/tk-r22.mp4",
    likes: 0,
    comments: [],
    tags: ["pozole", "jalisco", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "el.rincon.del.postre",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r23",
    user: "angelhcamara",
    displayName: "Ángel Hernández",
    caption: "Pozole estilo Jalisco. Fiestas patrias. Vía @angelhcamara",
    city: "Guadalajara",
    image: "/clips/tk-r23.jpg",
    video: "/clips/tk-r23.mp4",
    likes: 0,
    comments: [],
    tags: ["pozole", "jalisco", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "angelhcamara",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r24",
    user: "don.juan.ruiz.3",
    displayName: "Don Juan Ruiz",
    caption: "Centro histórico de Guadalajara. Vía @don.juan.ruiz.3",
    city: "Guadalajara",
    image: "/clips/tk-r24.jpg",
    video: "/clips/tk-r24.mp4",
    likes: 0,
    comments: [],
    tags: ["Guadalajara", "parati"],
    sound: "Sonido original",
    soundArtist: "don.juan.ruiz.3",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r25",
    user: "brillaconluz_",
    displayName: "Luz Elena",
    caption: "Caminar el corazón de Guadalajara. Vía @brillaconluz_",
    city: "Guadalajara",
    image: "/clips/tk-r25.jpg",
    video: "/clips/tk-r25.mp4",
    likes: 0,
    comments: [],
    tags: ["Guadalajara", "parati"],
    sound: "Sonido original",
    soundArtist: "brillaconluz_",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r26",
    user: "_vanessa.ae",
    displayName: "Vane",
    caption: "Mérida de noche. Centro histórico. Vía @_vanessa.ae",
    city: "Mérida",
    image: "/clips/tk-r26.jpg",
    video: "/clips/tk-r26.mp4",
    likes: 0,
    comments: [],
    tags: ["Merida", "Yucatan", "parati"],
    sound: "Sonido original",
    soundArtist: "_vanessa.ae",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r27",
    user: "cocinandoconmadre1",
    displayName: "Cocinando con madre",
    caption: "Tianguis en Chabacano. Vía @cocinandoconmadre1",
    city: "Ciudad de México",
    image: "/clips/tk-r27.jpg",
    video: "/clips/tk-r27.mp4",
    likes: 0,
    comments: [],
    tags: ["tianguis", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "cocinandoconmadre1",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r28",
    user: "soygiovalopez",
    displayName: "Giova",
    caption: "La afición en el Azteca. Vía @soygiovalopez",
    city: "Ciudad de México",
    image: "/clips/tk-r28.jpg",
    video: "/clips/tk-r28.mp4",
    likes: 0,
    comments: [],
    tags: ["futbol", "azteca", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "soygiovalopez",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r29",
    user: "donde.dann",
    displayName: "Donde Dann",
    caption: "Xochimilco en trajinera. Vía @donde.dann",
    city: "Ciudad de México",
    image: "/clips/tk-r29.jpg",
    video: "/clips/tk-r29.mp4",
    likes: 0,
    comments: [],
    tags: ["xochimilco", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "donde.dann",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r30",
    user: "carol_21.8",
    displayName: "Carol",
    caption: "Lady tacos de canasta, CDMX. Vía @carol_21.8",
    city: "Ciudad de México",
    image: "/clips/tk-r30.jpg",
    video: "/clips/tk-r30.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "canasta", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "carol_21.8",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r31",
    user: "guiacomidista",
    displayName: "Guía Comidista",
    caption: "Lady tacos de canasta. Sonido del antojo. Vía @guiacomidista",
    city: "Ciudad de México",
    image: "/clips/tk-r31.jpg",
    video: "/clips/tk-r31.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "canasta", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "guiacomidista",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r32",
    user: "arturoaguirree",
    displayName: "Arturo Aguirre",
    caption: "Churros cerca de la Catedral. Vía @arturoaguirree",
    city: "Ciudad de México",
    image: "/clips/tk-r32.jpg",
    video: "/clips/tk-r32.mp4",
    likes: 0,
    comments: [],
    tags: ["churros", "CDMX", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "arturoaguirree",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r33",
    user: "mudo2792",
    displayName: "Mudo",
    caption: "Mole de Oaxaca. Vía @mudo2792",
    city: "Oaxaca",
    image: "/clips/tk-r33.jpg",
    video: "/clips/tk-r33.mp4",
    likes: 0,
    comments: [],
    tags: ["mole", "oaxaca", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "mudo2792",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r34",
    user: "flakita7912",
    displayName: "Flakita",
    caption: "Mole oaxaqueño. Vía @flakita7912",
    city: "Oaxaca",
    image: "/clips/tk-r34.jpg",
    video: "/clips/tk-r34.mp4",
    likes: 0,
    comments: [],
    tags: ["mole", "oaxaca", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "flakita7912",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r35",
    user: "naturalezaanahi",
    displayName: "Anahí",
    caption: "Primera vez el mole poblano. Vía @naturalezaanahi",
    city: "Puebla",
    image: "/clips/tk-r35.jpg",
    video: "/clips/tk-r35.mp4",
    likes: 0,
    comments: [],
    tags: ["mole", "puebla", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "naturalezaanahi",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r36",
    user: "ojos_de_turistashop",
    displayName: "Ojos de turista",
    caption: "Birria de Jalisco. Tierra del tequila. Vía @ojos_de_turistashop",
    city: "Guadalajara",
    image: "/clips/tk-r36.jpg",
    video: "/clips/tk-r36.mp4",
    likes: 0,
    comments: [],
    tags: ["birria", "jalisco", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "ojos_de_turistashop",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r37",
    user: "te.lo.recomiendo10",
    displayName: "Te lo recomiendo",
    caption: "Birria La Barca, Mercado Juárez. Vía @te.lo.recomiendo10",
    city: "Guadalajara",
    image: "/clips/tk-r37.jpg",
    video: "/clips/tk-r37.mp4",
    likes: 0,
    comments: [],
    tags: ["birria", "jalisco", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "te.lo.recomiendo10",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r38",
    user: "yabbygls",
    displayName: "Yabby",
    caption: "La cochinita pibil se cocina bajo tierra. Vía @yabbygls",
    city: "Mérida",
    image: "/clips/tk-r38.jpg",
    video: "/clips/tk-r38.mp4",
    likes: 0,
    comments: [],
    tags: ["cochinita", "yucatan", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "yabbygls",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r39",
    user: "elfoodiedelbarrio",
    displayName: "El foodie del barrio",
    caption: "Cochinita en La Original Yucateca. Vía @elfoodiedelbarrio",
    city: "Mérida",
    image: "/clips/tk-r39.jpg",
    video: "/clips/tk-r39.mp4",
    likes: 0,
    comments: [],
    tags: ["cochinita", "yucatan", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "elfoodiedelbarrio",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r40",
    user: "soysammendoza",
    displayName: "Sam Mendoza",
    caption: "Palenque Los Abuelos. Mezcal de agave. Vía @soysammendoza",
    city: "Oaxaca",
    image: "/clips/tk-r40.jpg",
    video: "/clips/tk-r40.mp4",
    likes: 0,
    comments: [],
    tags: ["mezcal", "oaxaca", "parati"],
    sound: "Sonido original",
    soundArtist: "soysammendoza",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r41",
    user: "experiencias.con.s",
    displayName: "Experiencias con S",
    caption: "Visitar un palenque de mezcal. Vía @experiencias.con.s",
    city: "Oaxaca",
    image: "/clips/tk-r41.jpg",
    video: "/clips/tk-r41.mp4",
    likes: 0,
    comments: [],
    tags: ["mezcal", "oaxaca", "parati"],
    sound: "Sonido original",
    soundArtist: "experiencias.con.s",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r42",
    user: "selene.salazar.asesora",
    displayName: "Selene Salazar",
    caption: "Playa del Carmen. Más que una playa. Vía @selene.salazar.asesora",
    city: "Cancún",
    image: "/clips/tk-r42.jpg",
    video: "/clips/tk-r42.mp4",
    likes: 0,
    comments: [],
    tags: ["playa", "caribe", "parati"],
    sound: "Sonido original",
    soundArtist: "selene.salazar.asesora",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r43",
    user: "reelsintime0",
    displayName: "Reels in time",
    caption: "El Cerro de la Silla. Vía @reelsintime0",
    city: "Monterrey",
    image: "/clips/tk-r43.jpg",
    video: "/clips/tk-r43.mp4",
    likes: 0,
    comments: [],
    tags: ["Monterrey", "parati"],
    sound: "Sonido original",
    soundArtist: "reelsintime0",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r44",
    user: "joelramd_art",
    displayName: "Joel Ramd",
    caption: "Coatíes en el Cerro de la Silla. Vía @joelramd_art",
    city: "Monterrey",
    image: "/clips/tk-r44.jpg",
    video: "/clips/tk-r44.mp4",
    likes: 0,
    comments: [],
    tags: ["Monterrey", "parati"],
    sound: "Sonido original",
    soundArtist: "joelramd_art",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r45",
    user: "_ale.cld",
    displayName: "Ale",
    caption: "Centro de Tijuana. Vía @_ale.cld",
    city: "Tijuana",
    image: "/clips/tk-r45.jpg",
    video: "/clips/tk-r45.mp4",
    likes: 0,
    comments: [],
    tags: ["Tijuana", "parati"],
    sound: "Sonido original",
    soundArtist: "_ale.cld",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r46",
    user: "gloriamv12",
    displayName: "Gloria",
    caption: "Bordado del Istmo. Vía @gloriamv12",
    city: "Oaxaca",
    image: "/clips/tk-r46.jpg",
    video: "/clips/tk-r46.mp4",
    likes: 0,
    comments: [],
    tags: ["istmo", "oaxaca", "parati"],
    sound: "Sonido original",
    soundArtist: "gloriamv12",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r47",
    user: "taniizquierdo",
    displayName: "Tania Izquierdo",
    caption: "Palenque desde arriba. Vía @taniizquierdo",
    city: "Chiapas",
    image: "/clips/tk-r47.jpg",
    video: "/clips/tk-r47.mp4",
    likes: 0,
    comments: [],
    tags: ["palenque", "chiapas", "historia", "parati"],
    sound: "Sonido original",
    soundArtist: "taniizquierdo",
    series: "HistorySnack",
    country: "MX",
  },
  {
    id: "tk-r48",
    user: "experienciasbyjenn",
    displayName: "Jenn",
    caption: "Zona arqueológica de Palenque. Vía @experienciasbyjenn",
    city: "Chiapas",
    image: "/clips/tk-r48.jpg",
    video: "/clips/tk-r48.mp4",
    likes: 0,
    comments: [],
    tags: ["palenque", "chiapas", "historia", "parati"],
    sound: "Sonido original",
    soundArtist: "experienciasbyjenn",
    series: "HistorySnack",
    country: "MX",
  },
  {
    id: "tk-r49",
    user: "gaelblogs_",
    displayName: "Gael",
    caption: "Casa Azul. Donde vivió Frida. Vía @gaelblogs_",
    city: "Ciudad de México",
    image: "/clips/tk-r49.jpg",
    video: "/clips/tk-r49.mp4",
    likes: 0,
    comments: [],
    tags: ["frida", "CDMX", "historia", "parati"],
    sound: "Sonido original",
    soundArtist: "gaelblogs_",
    series: "HistorySnack",
    country: "MX",
  },
  {
    id: "tk-r50",
    user: "lennysayas",
    displayName: "Lenny Sayas",
    caption: "Los voladores de Papantla. Vía @lennysayas",
    city: "Veracruz",
    image: "/clips/tk-r50.jpg",
    video: "/clips/tk-r50.mp4",
    likes: 0,
    comments: [],
    tags: ["voladores", "papantla", "parati"],
    sound: "Sonido original",
    soundArtist: "lennysayas",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r51",
    user: "araceliaguirre61",
    displayName: "Araceli Aguirre",
    caption: "Voladores de Papantla. Vía @araceliaguirre61",
    city: "Puebla",
    image: "/clips/tk-r51.jpg",
    video: "/clips/tk-r51.mp4",
    likes: 0,
    comments: [],
    tags: ["voladores", "papantla", "parati"],
    sound: "Sonido original",
    soundArtist: "araceliaguirre61",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r52",
    user: "grisz2",
    displayName: "Gris",
    caption: "Cumbia sonidera. Vía @grisz2",
    city: "Ciudad de México",
    image: "/clips/tk-r52.jpg",
    video: "/clips/tk-r52.mp4",
    likes: 0,
    comments: [],
    tags: ["cumbia", "sonidero", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "grisz2",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r53",
    user: "vivegro",
    displayName: "Vive Gro",
    caption: "Calles de Taxco al atardecer. Vía @vivegro",
    city: "Taxco",
    image: "/clips/tk-r53.jpg",
    video: "/clips/tk-r53.mp4",
    likes: 0,
    comments: [],
    tags: ["taxco", "guerrero", "parati"],
    sound: "Sonido original",
    soundArtist: "vivegro",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r54",
    user: "tabatajaliloficial",
    displayName: "Tabata Jalil",
    caption: "Chile en nogada. Se come la bandera. Vía @tabatajaliloficial",
    city: "Puebla",
    image: "/clips/tk-r54.jpg",
    video: "/clips/tk-r54.mp4",
    likes: 0,
    comments: [],
    tags: ["nogada", "puebla", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "tabatajaliloficial",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r55",
    user: "informacion.tzont",
    displayName: "Tzont",
    caption: "San Juan Chamula. Vía @informacion.tzont",
    city: "Chiapas",
    image: "/clips/tk-r55.jpg",
    video: "/clips/tk-r55.mp4",
    likes: 0,
    comments: [],
    tags: ["chamula", "chiapas", "parati"],
    sound: "Sonido original",
    soundArtist: "informacion.tzont",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r56",
    user: "mesoaventura",
    displayName: "Mesoaventura",
    caption: "San Cristóbal de las Casas. Vía @mesoaventura",
    city: "Chiapas",
    image: "/clips/tk-r56.jpg",
    video: "/clips/tk-r56.mp4",
    likes: 0,
    comments: [],
    tags: ["chiapas", "sancristobal", "parati"],
    sound: "Sonido original",
    soundArtist: "mesoaventura",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r57",
    user: "makylu0303",
    displayName: "Makylu",
    caption: "Tlayuda con chapulines. Sabor oaxaqueño. Vía @makylu0303",
    city: "Oaxaca",
    image: "/clips/tk-r57.jpg",
    video: "/clips/tk-r57.mp4",
    likes: 0,
    comments: [],
    tags: ["tlayuda", "oaxaca", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "makylu0303",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r58",
    user: "giselmerino",
    displayName: "Gisel Merino",
    caption: "Tlayudas oaxaqueñas, a mi estilo. Vía @giselmerino",
    city: "Oaxaca",
    image: "/clips/tk-r58.jpg",
    video: "/clips/tk-r58.mp4",
    likes: 0,
    comments: [],
    tags: ["tlayuda", "oaxaca", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "giselmerino",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r59",
    user: "parceromn2",
    displayName: "Parce",
    caption: "Carnitas, el mero mero. Vía @parceromn2",
    city: "Morelia",
    image: "/clips/tk-r59.jpg",
    video: "/clips/tk-r59.mp4",
    likes: 0,
    comments: [],
    tags: ["carnitas", "michoacan", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "parceromn2",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r60",
    user: "ambarr.arq",
    displayName: "Ambar",
    caption: "Datos del pueblo mágico de Tequila. Vía @ambarr.arq",
    city: "Jalisco",
    image: "/clips/tk-r60.jpg",
    video: "/clips/tk-r60.mp4",
    likes: 0,
    comments: [],
    tags: ["tequila", "jalisco", "parati"],
    sound: "Sonido original",
    soundArtist: "ambarr.arq",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r61",
    user: "benittfu1ir",
    displayName: "Benitt",
    caption: "Tequila, Jalisco. Pueblo mágico. Vía @benittfu1ir",
    city: "Jalisco",
    image: "/clips/tk-r61.jpg",
    video: "/clips/tk-r61.mp4",
    likes: 0,
    comments: [],
    tags: ["tequila", "jalisco", "parati"],
    sound: "Sonido original",
    soundArtist: "benittfu1ir",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r62",
    user: "vida_maggie",
    displayName: "Maggie",
    caption: "Callejoneada en Guanajuato. Vía @vida_maggie",
    city: "Guanajuato",
    image: "/clips/tk-r62.jpg",
    video: "/clips/tk-r62.mp4",
    likes: 0,
    comments: [],
    tags: ["guanajuato", "callejoneada", "parati"],
    sound: "Sonido original",
    soundArtist: "vida_maggie",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r63",
    user: "darianita2303",
    displayName: "Dariana",
    caption: "El callejón del beso. Vía @darianita2303",
    city: "Guanajuato",
    image: "/clips/tk-r63.jpg",
    video: "/clips/tk-r63.mp4",
    likes: 0,
    comments: [],
    tags: ["guanajuato", "parati"],
    sound: "Sonido original",
    soundArtist: "darianita2303",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r64",
    user: "garcia_charly",
    displayName: "Charly García",
    caption: "Folklórico. Viva México. Vía @garcia_charly",
    city: "Ciudad de México",
    image: "/clips/tk-r64.jpg",
    video: "/clips/tk-r64.mp4",
    likes: 0,
    comments: [],
    tags: ["folklorico", "mexico", "parati"],
    sound: "Sonido original",
    soundArtist: "garcia_charly",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r65",
    user: "milalove2010",
    displayName: "Mila",
    caption: "Folklórico en fiestas patrias. Vía @milalove2010",
    city: "Ciudad de México",
    image: "/clips/tk-r65.jpg",
    video: "/clips/tk-r65.mp4",
    likes: 0,
    comments: [],
    tags: ["folklorico", "mexico", "parati"],
    sound: "Sonido original",
    soundArtist: "milalove2010",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r66",
    user: "wildflavorsoftheworld",
    displayName: "Wild Flavors",
    caption: "Pirámide en Tulum. Vía @wildflavorsoftheworld",
    city: "Cancún",
    image: "/clips/tk-r66.jpg",
    video: "/clips/tk-r66.mp4",
    likes: 0,
    comments: [],
    tags: ["tulum", "maya", "historia", "parati"],
    sound: "Sonido original",
    soundArtist: "wildflavorsoftheworld",
    series: "HistorySnack",
    country: "MX",
  },
  {
    id: "tk-r67",
    user: "adventure.omh",
    displayName: "Adventure OMH",
    caption: "El Arco de Cabo San Lucas. Vía @adventure.omh",
    city: "La Paz",
    image: "/clips/tk-r67.jpg",
    video: "/clips/tk-r67.mp4",
    likes: 0,
    comments: [],
    tags: ["cabo", "baja", "parati"],
    sound: "Sonido original",
    soundArtist: "adventure.omh",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r68",
    user: "itzzellyylcabrera25",
    displayName: "Itzel Cabrera",
    caption: "El Arco, donde se encuentran los mares. Vía @itzzellyylcabrera25",
    city: "La Paz",
    image: "/clips/tk-r68.jpg",
    video: "/clips/tk-r68.mp4",
    likes: 0,
    comments: [],
    tags: ["cabo", "baja", "parati"],
    sound: "Sonido original",
    soundArtist: "itzzellyylcabrera25",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r69",
    user: "janethjeni12",
    displayName: "Janeth",
    caption: "Caminando el centro de Zacatecas. Vía @janethjeni12",
    city: "Zacatecas",
    image: "/clips/tk-r69.jpg",
    video: "/clips/tk-r69.mp4",
    likes: 0,
    comments: [],
    tags: ["zacatecas", "parati"],
    sound: "Sonido original",
    soundArtist: "janethjeni12",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r70",
    user: "ric.villagrana",
    displayName: "Ric Villagrana",
    caption: "Lluvia sobre la cantera rosa. Vía @ric.villagrana",
    city: "Zacatecas",
    image: "/clips/tk-r70.jpg",
    video: "/clips/tk-r70.mp4",
    likes: 0,
    comments: [],
    tags: ["zacatecas", "parati"],
    sound: "Sonido original",
    soundArtist: "ric.villagrana",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r71",
    user: "javiiii064",
    displayName: "Javi",
    caption: "La Catedral de Morelia. Vía @javiiii064",
    city: "Morelia",
    image: "/clips/tk-r71.jpg",
    video: "/clips/tk-r71.mp4",
    likes: 0,
    comments: [],
    tags: ["morelia", "michoacan", "parati"],
    sound: "Sonido original",
    soundArtist: "javiiii064",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r72",
    user: "anthonyandrewtrujillo",
    displayName: "Anthony Trujillo",
    caption: "Catedral de Morelia. Vía @anthonyandrewtrujillo",
    city: "Morelia",
    image: "/clips/tk-r72.jpg",
    video: "/clips/tk-r72.mp4",
    likes: 0,
    comments: [],
    tags: ["morelia", "michoacan", "parati"],
    sound: "Sonido original",
    soundArtist: "anthonyandrewtrujillo",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r73",
    user: "los.jimaveracruz",
    displayName: "Los Jima",
    caption: "Danzón en Veracruz. Vía @los.jimaveracruz",
    city: "Veracruz",
    image: "/clips/tk-r73.jpg",
    video: "/clips/tk-r73.mp4",
    likes: 0,
    comments: [],
    tags: ["danzon", "veracruz", "parati"],
    sound: "Sonido original",
    soundArtist: "los.jimaveracruz",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r74",
    user: "katemandrygina",
    displayName: "Kate",
    caption: "Danzón veracruzano en Tuxpan. Vía @katemandrygina",
    city: "Veracruz",
    image: "/clips/tk-r74.jpg",
    video: "/clips/tk-r74.mp4",
    likes: 0,
    comments: [],
    tags: ["danzon", "veracruz", "parati"],
    sound: "Sonido original",
    soundArtist: "katemandrygina",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r75",
    user: "jezziel.sofia",
    displayName: "Jezziel",
    caption: "Alebrijes. Que alguien que sí le sepa diga. Vía @jezziel.sofia",
    city: "Oaxaca",
    image: "/clips/tk-r75.jpg",
    video: "/clips/tk-r75.mp4",
    likes: 0,
    comments: [],
    tags: ["alebrijes", "oaxaca", "parati"],
    sound: "Sonido original",
    soundArtist: "jezziel.sofia",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r76",
    user: "yolotzindemexico",
    displayName: "Yolotzin",
    caption: "Esto es talavera. Y esto también. Vía @yolotzindemexico",
    city: "Puebla",
    image: "/clips/tk-r76.jpg",
    video: "/clips/tk-r76.mp4",
    likes: 0,
    comments: [],
    tags: ["talavera", "puebla", "parati"],
    sound: "Sonido original",
    soundArtist: "yolotzindemexico",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r77",
    user: "evee_brambila",
    displayName: "Eve Brambila",
    caption: "Traje wixárika. Graduación huichol. Vía @evee_brambila",
    city: "Nayarit",
    image: "/clips/tk-r77.jpg",
    video: "/clips/tk-r77.mp4",
    likes: 0,
    comments: [],
    tags: ["huichol", "nayarit", "parati"],
    sound: "Sonido original",
    soundArtist: "evee_brambila",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r78",
    user: "lalocarmona5",
    displayName: "Lalo Carmona",
    caption: "El cempasúchil ilumina el camino de regreso. Vía @lalocarmona5",
    city: "Ciudad de México",
    image: "/clips/tk-r78.jpg",
    video: "/clips/tk-r78.mp4",
    likes: 0,
    comments: [],
    tags: ["muertos", "cempasuchil", "parati"],
    sound: "Sonido original",
    soundArtist: "lalocarmona5",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r79",
    user: "swaghermosillo2",
    displayName: "Swag Hermosillo",
    caption: "En la CDMX la quesadilla no lleva queso. Vía @swaghermosillo2",
    city: "Ciudad de México",
    image: "/clips/tk-r79.jpg",
    video: "/clips/tk-r79.mp4",
    likes: 0,
    comments: [],
    tags: ["quesadilla", "CDMX", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "swaghermosillo2",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r80",
    user: "valdy_cortes",
    displayName: "Valdy Cortés",
    caption: "Paseo en el malecón de Mazatlán. Vía @valdy_cortes",
    city: "Mazatlán",
    image: "/clips/tk-r80.jpg",
    video: "/clips/tk-r80.mp4",
    likes: 0,
    comments: [],
    tags: ["mazatlan", "malecon", "parati"],
    sound: "Sonido original",
    soundArtist: "valdy_cortes",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r81",
    user: "miguelvargas_0",
    displayName: "Miguel Vargas",
    caption: "La Guelaguetza. La diosa centéotl. Vía @miguelvargas_0",
    city: "Oaxaca",
    image: "/clips/tk-r81.jpg",
    video: "/clips/tk-r81.mp4",
    likes: 0,
    comments: [],
    tags: ["guelaguetza", "oaxaca", "parati"],
    sound: "Sonido original",
    soundArtist: "miguelvargas_0",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r82",
    user: "alberto.suarez1",
    displayName: "Alberto Suárez",
    caption: "Empieza la fiesta más grande de México. Vía @alberto.suarez1",
    city: "Oaxaca",
    image: "/clips/tk-r82.jpg",
    video: "/clips/tk-r82.mp4",
    likes: 0,
    comments: [],
    tags: ["guelaguetza", "oaxaca", "parati"],
    sound: "Sonido original",
    soundArtist: "alberto.suarez1",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r83",
    user: "eduardovargas.photofilm",
    displayName: "Eduardo Vargas",
    caption: "Hierve el Agua. El agua se queda quieta. Vía @eduardovargas.photofilm",
    city: "Oaxaca",
    image: "/clips/tk-r83.jpg",
    video: "/clips/tk-r83.mp4",
    likes: 0,
    comments: [],
    tags: ["oaxaca", "hierveelagua", "parati"],
    sound: "Sonido original",
    soundArtist: "eduardovargas.photofilm",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r84",
    user: "soyblakewebb",
    displayName: "Blake Webb",
    caption: "Hierve el Agua. Viva México. Vía @soyblakewebb",
    city: "Oaxaca",
    image: "/clips/tk-r84.jpg",
    video: "/clips/tk-r84.mp4",
    likes: 0,
    comments: [],
    tags: ["oaxaca", "hierveelagua", "parati"],
    sound: "Sonido original",
    soundArtist: "soyblakewebb",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r85",
    user: "culturanayaritt",
    displayName: "Cultura Nayarit",
    caption: "Pescado zarandeado. Del mar de Nayarit. Vía @culturanayaritt",
    city: "Nayarit",
    image: "/clips/tk-r85.jpg",
    video: "/clips/tk-r85.mp4",
    likes: 0,
    comments: [],
    tags: ["zarandeado", "nayarit", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "culturanayaritt",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r86",
    user: "nayla_fotografa",
    displayName: "Nayla",
    caption: "Campeche y su centro histórico. Vía @nayla_fotografa",
    city: "Campeche",
    image: "/clips/tk-r86.jpg",
    video: "/clips/tk-r86.mp4",
    likes: 0,
    comments: [],
    tags: ["campeche", "parati"],
    sound: "Sonido original",
    soundArtist: "nayla_fotografa",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r87",
    user: "aaaharon",
    displayName: "Aharon",
    caption: "Calle 59, Campeche. Vía @aaaharon",
    city: "Campeche",
    image: "/clips/tk-r87.jpg",
    video: "/clips/tk-r87.mp4",
    likes: 0,
    comments: [],
    tags: ["campeche", "parati"],
    sound: "Sonido original",
    soundArtist: "aaaharon",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r88",
    user: "tanyafreedom",
    displayName: "Tanya",
    caption: "Bacalar. Un paraíso en México. Vía @tanyafreedom",
    city: "Cancún",
    image: "/clips/tk-r88.jpg",
    video: "/clips/tk-r88.mp4",
    likes: 0,
    comments: [],
    tags: ["bacalar", "caribe", "parati"],
    sound: "Sonido original",
    soundArtist: "tanyafreedom",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r89",
    user: "adrianferegrin0",
    displayName: "Adrián",
    caption: "La Peña de Bernal. Vía @adrianferegrin0",
    city: "Querétaro",
    image: "/clips/tk-r89.jpg",
    video: "/clips/tk-r89.mp4",
    likes: 0,
    comments: [],
    tags: ["bernal", "queretaro", "parati"],
    sound: "Sonido original",
    soundArtist: "adrianferegrin0",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r90",
    user: "donjuanitzel",
    displayName: "Itzel",
    caption: "Peña de Bernal. Guarden este lugar. Vía @donjuanitzel",
    city: "Querétaro",
    image: "/clips/tk-r90.jpg",
    video: "/clips/tk-r90.mp4",
    likes: 0,
    comments: [],
    tags: ["bernal", "queretaro", "parati"],
    sound: "Sonido original",
    soundArtist: "donjuanitzel",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r91",
    user: "jaime.ugarte",
    displayName: "Jaime Ugarte",
    caption: "Real de Catorce. Pueblo mágico. Vía @jaime.ugarte",
    city: "San Miguel de Allende",
    image: "/clips/tk-r91.jpg",
    video: "/clips/tk-r91.mp4",
    likes: 0,
    comments: [],
    tags: ["catorce", "parati"],
    sound: "Sonido original",
    soundArtist: "jaime.ugarte",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r92",
    user: "lamaggy55",
    displayName: "Maggy",
    caption: "Real de Catorce. Misterioso y mágico. Vía @lamaggy55",
    city: "San Miguel de Allende",
    image: "/clips/tk-r92.jpg",
    video: "/clips/tk-r92.mp4",
    likes: 0,
    comments: [],
    tags: ["catorce", "parati"],
    sound: "Sonido original",
    soundArtist: "lamaggy55",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r93",
    user: "saamslz",
    displayName: "Saam",
    caption: "Rincones de San Miguel de Allende. Vía @saamslz",
    city: "San Miguel de Allende",
    image: "/clips/tk-r93.jpg",
    video: "/clips/tk-r93.mp4",
    likes: 0,
    comments: [],
    tags: ["sanmiguel", "parati"],
    sound: "Sonido original",
    soundArtist: "saamslz",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r94",
    user: "coronadofrank",
    displayName: "Frank Coronado",
    caption: "Noche de Rábanos. Vía @coronadofrank",
    city: "Oaxaca",
    image: "/clips/tk-r94.jpg",
    video: "/clips/tk-r94.mp4",
    likes: 0,
    comments: [],
    tags: ["rabanos", "oaxaca", "parati"],
    sound: "Sonido original",
    soundArtist: "coronadofrank",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r95",
    user: "marioriestrapina",
    displayName: "Mario Riestra",
    caption: "El origen de la cemita poblana. Vía @marioriestrapina",
    city: "Puebla",
    image: "/clips/tk-r95.jpg",
    video: "/clips/tk-r95.mp4",
    likes: 0,
    comments: [],
    tags: ["cemita", "puebla", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "marioriestrapina",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r96",
    user: "arturoalvaradoo",
    displayName: "Arturo Alvarado",
    caption: "Dos tepacherías en la CDMX. Vía @arturoalvaradoo",
    city: "Ciudad de México",
    image: "/clips/tk-r96.jpg",
    video: "/clips/tk-r96.mp4",
    likes: 0,
    comments: [],
    tags: ["tepache", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "arturoalvaradoo",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r97",
    user: "mxartesanal",
    displayName: "MX Artesanal",
    caption: "Tepache. Bebida ancestral. Vía @mxartesanal",
    city: "Ciudad de México",
    image: "/clips/tk-r97.jpg",
    video: "/clips/tk-r97.mp4",
    likes: 0,
    comments: [],
    tags: ["tepache", "parati"],
    sound: "Sonido original",
    soundArtist: "mxartesanal",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r98",
    user: "uriel.bv97",
    displayName: "Uriel",
    caption: "Pulquería en la CDMX. Vía @uriel.bv97",
    city: "Ciudad de México",
    image: "/clips/tk-r98.jpg",
    video: "/clips/tk-r98.mp4",
    likes: 0,
    comments: [],
    tags: ["pulque", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "uriel.bv97",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r99",
    user: "eduardostichfoto",
    displayName: "Eduardo Stich",
    caption: "Ir a una pulquería en la CDMX. Vía @eduardostichfoto",
    city: "Ciudad de México",
    image: "/clips/tk-r99.jpg",
    video: "/clips/tk-r99.mp4",
    likes: 0,
    comments: [],
    tags: ["pulque", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "eduardostichfoto",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r100",
    user: "luceroreguero",
    displayName: "Lucero Reguero",
    caption: "Chocolate casero tabasqueño. Vía @luceroreguero",
    city: "Tabasco",
    image: "/clips/tk-r100.jpg",
    video: "/clips/tk-r100.mp4",
    likes: 0,
    comments: [],
    tags: ["cacao", "tabasco", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "luceroreguero",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r101",
    user: "selenaobregon222",
    displayName: "Selena Obregón",
    caption: "Teleférico en las Barrancas del Cobre. Vía @selenaobregon222",
    city: "Chihuahua",
    image: "/clips/tk-r101.jpg",
    video: "/clips/tk-r101.mp4",
    likes: 0,
    comments: [],
    tags: ["barrancas", "chihuahua", "parati"],
    sound: "Sonido original",
    soundArtist: "selenaobregon222",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r102",
    user: "normaolivaas",
    displayName: "Norma Oliva",
    caption: "Holbox. Recomendación honesta. Vía @normaolivaas",
    city: "Cancún",
    image: "/clips/tk-r102.jpg",
    video: "/clips/tk-r102.mp4",
    likes: 0,
    comments: [],
    tags: ["holbox", "caribe", "parati"],
    sound: "Sonido original",
    soundArtist: "normaolivaas",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r103",
    user: "mr.chivafan",
    displayName: "Mr Chiva Fan",
    caption: "Viva México y viva Chivas. Vía @mr.chivafan",
    city: "Guadalajara",
    image: "/clips/tk-r103.jpg",
    video: "/clips/tk-r103.mp4",
    likes: 0,
    comments: [],
    tags: ["chivas", "futbol", "parati"],
    sound: "Sonido original",
    soundArtist: "mr.chivafan",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r104",
    user: "fogson._",
    displayName: "Fogson",
    caption: "Chivas. Aún así te amo. Vía @fogson._",
    city: "Guadalajara",
    image: "/clips/tk-r104.jpg",
    video: "/clips/tk-r104.mp4",
    likes: 0,
    comments: [],
    tags: ["chivas", "futbol", "parati"],
    sound: "Sonido original",
    soundArtist: "fogson._",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r105",
    user: "charly4457",
    displayName: "Charly",
    caption: "Mariposa monarca. Noviembre a marzo. Vía @charly4457",
    city: "Morelia",
    image: "/clips/tk-r105.jpg",
    video: "/clips/tk-r105.mp4",
    likes: 0,
    comments: [],
    tags: ["monarca", "michoacan", "parati"],
    sound: "Sonido original",
    soundArtist: "charly4457",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r106",
    user: "visit_michoacan",
    displayName: "Visit Michoacán",
    caption: "La monarca pinta los bosques de Michoacán. Vía @visit_michoacan",
    city: "Morelia",
    image: "/clips/tk-r106.jpg",
    video: "/clips/tk-r106.mp4",
    likes: 0,
    comments: [],
    tags: ["monarca", "michoacan", "parati"],
    sound: "Sonido original",
    soundArtist: "visit_michoacan",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r107",
    user: "jalisco.esmexico",
    displayName: "Jalisco es México",
    caption: "Jarabe tapatío. Jalisco se siente. Vía @jalisco.esmexico",
    city: "Guadalajara",
    image: "/clips/tk-r107.jpg",
    video: "/clips/tk-r107.mp4",
    likes: 0,
    comments: [],
    tags: ["jarabe", "jalisco", "parati"],
    sound: "Sonido original",
    soundArtist: "jalisco.esmexico",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r108",
    user: "joa.e.m",
    displayName: "Joa",
    caption: "Jarabe en fiestas patrias. Vía @joa.e.m",
    city: "Guadalajara",
    image: "/clips/tk-r108.jpg",
    video: "/clips/tk-r108.mp4",
    likes: 0,
    comments: [],
    tags: ["jarabe", "folklorico", "parati"],
    sound: "Sonido original",
    soundArtist: "joa.e.m",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r109",
    user: "soymontegreen",
    displayName: "Monte Green",
    caption: "El suadero representa la calle. Vía @soymontegreen",
    city: "Ciudad de México",
    image: "/clips/tk-r109.jpg",
    video: "/clips/tk-r109.mp4",
    likes: 0,
    comments: [],
    tags: ["suadero", "tacos", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "soymontegreen",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r110",
    user: "chuladademaizprieto_",
    displayName: "Chulada de Maíz",
    caption: "Los mejores tacos de suadero. Vía @chuladademaizprieto_",
    city: "Ciudad de México",
    image: "/clips/tk-r110.jpg",
    video: "/clips/tk-r110.mp4",
    likes: 0,
    comments: [],
    tags: ["suadero", "tacos", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "chuladademaizprieto_",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r111",
    user: "mianbarrera",
    displayName: "Mian Barrera",
    caption: "Palacio de Bellas Artes. Vía @mianbarrera",
    city: "Ciudad de México",
    image: "/clips/tk-r111.jpg",
    video: "/clips/tk-r111.mp4",
    likes: 0,
    comments: [],
    tags: ["bellasartes", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "mianbarrera",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r112",
    user: "danyardz8",
    displayName: "Dany",
    caption: "Bellas Artes, CDMX. Vía @danyardz8",
    city: "Ciudad de México",
    image: "/clips/tk-r112.jpg",
    video: "/clips/tk-r112.mp4",
    likes: 0,
    comments: [],
    tags: ["bellasartes", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "danyardz8",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r113",
    user: "edgar.salas94",
    displayName: "Edgar Salas",
    caption: "Cenote Saamal, Valladolid. Vía @edgar.salas94",
    city: "Mérida",
    image: "/clips/tk-r113.jpg",
    video: "/clips/tk-r113.mp4",
    likes: 0,
    comments: [],
    tags: ["cenote", "valladolid", "yucatan", "parati"],
    sound: "Sonido original",
    soundArtist: "edgar.salas94",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r114",
    user: "quepasaguadalajara",
    displayName: "Qué pasa Guadalajara",
    caption: "Se tenía que decir, tapatíos. Torta ahogada. Vía @quepasaguadalajara",
    city: "Guadalajara",
    image: "/clips/tk-r114.jpg",
    video: "/clips/tk-r114.mp4",
    likes: 0,
    comments: [],
    tags: ["torta", "ahogada", "gdl", "parati"],
    sound: "Sonido original",
    soundArtist: "quepasaguadalajara",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r115",
    user: "descubrequehacer",
    displayName: "Descubre qué hacer",
    caption: "Sueño de una tarde dominical. Rivera. Vía @descubrequehacer",
    city: "Ciudad de México",
    image: "/clips/tk-r115.jpg",
    video: "/clips/tk-r115.mp4",
    likes: 0,
    comments: [],
    tags: ["rivera", "mural", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "descubrequehacer",
    series: "HistorySnack",
    country: "MX",
  },
  {
    id: "tk-r116",
    user: "monicasauza2",
    displayName: "Mónica Sauza",
    caption: "El mural de Diego Rivera. Vía @monicasauza2",
    city: "Ciudad de México",
    image: "/clips/tk-r116.jpg",
    video: "/clips/tk-r116.mp4",
    likes: 0,
    comments: [],
    tags: ["rivera", "mural", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "monicasauza2",
    series: "HistorySnack",
    country: "MX",
  },
  {
    id: "tk-r117",
    user: "luis.rivas.aguilar",
    displayName: "Luis Rivas",
    caption: "Ajolotito rumbo al Mictlán. Vía @luis.rivas.aguilar",
    city: "Ciudad de México",
    image: "/clips/tk-r117.jpg",
    video: "/clips/tk-r117.mp4",
    likes: 0,
    comments: [],
    tags: ["ajolote", "mexico", "parati"],
    sound: "Sonido original",
    soundArtist: "luis.rivas.aguilar",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r118",
    user: "poderanimal22",
    displayName: "Poder Animal",
    caption: "El ajolote. Un animal de este país. Vía @poderanimal22",
    city: "Ciudad de México",
    image: "/clips/tk-r118.jpg",
    video: "/clips/tk-r118.mp4",
    likes: 0,
    comments: [],
    tags: ["ajolote", "mexico", "parati"],
    sound: "Sonido original",
    soundArtist: "poderanimal22",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r119",
    user: "ifthebootfitzj4",
    displayName: "Bootfitz",
    caption: "Escaramuza. Mi niña y su equipo. Vía @ifthebootfitzj4",
    city: "Guadalajara",
    image: "/clips/tk-r119.jpg",
    video: "/clips/tk-r119.mp4",
    likes: 0,
    comments: [],
    tags: ["escaramuza", "charro", "parati"],
    sound: "Sonido original",
    soundArtist: "ifthebootfitzj4",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r120",
    user: "frankcool.24",
    displayName: "Frank Cool",
    caption: "Memelas baratas en la central. Vía @frankcool.24",
    city: "Oaxaca",
    image: "/clips/tk-r120.jpg",
    video: "/clips/tk-r120.mp4",
    likes: 0,
    comments: [],
    tags: ["memelas", "oaxaca", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "frankcool.24",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r121",
    user: "serggarciamx",
    displayName: "Serg García",
    caption: "Conchas que sí dan ganas. Vía @serggarciamx",
    city: "Ciudad de México",
    image: "/clips/tk-r121.jpg",
    video: "/clips/tk-r121.mp4",
    likes: 0,
    comments: [],
    tags: ["concha", "pan", "parati"],
    sound: "Sonido original",
    soundArtist: "serggarciamx",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r122",
    user: "sanmigueldeallende.mx",
    displayName: "San Miguel",
    caption: "La concha. Pan dulce mexicano. Vía @sanmigueldeallende.mx",
    city: "San Miguel de Allende",
    image: "/clips/tk-r122.jpg",
    video: "/clips/tk-r122.mp4",
    likes: 0,
    comments: [],
    tags: ["concha", "pan", "parati"],
    sound: "Sonido original",
    soundArtist: "sanmigueldeallende.mx",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r123",
    user: "aleiramrodrguez4",
    displayName: "Aleiram",
    caption: "Cascadas de Agua Azul. Vía @aleiramrodrguez4",
    city: "Chiapas",
    image: "/clips/tk-r123.jpg",
    video: "/clips/tk-r123.mp4",
    likes: 0,
    comments: [],
    tags: ["aguaazul", "chiapas", "parati"],
    sound: "Sonido original",
    soundArtist: "aleiramrodrguez4",
    series: "RegionalSpotlight",
    country: "MX",
  },
  {
    id: "tk-r124",
    user: "miguelrodeloo",
    displayName: "Miguel Rodeloo",
    caption: "Así se baila la banda. Vía @miguelrodeloo",
    city: "Mazatlán",
    image: "/clips/tk-r124.jpg",
    video: "/clips/tk-r124.mp4",
    likes: 0,
    comments: [],
    tags: ["banda", "sinaloa", "parati"],
    sound: "Sonido original",
    soundArtist: "miguelrodeloo",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r125",
    user: "charly_moreno_",
    displayName: "Charly Moreno",
    caption: "Así se baila en Culiacán. Vía @charly_moreno_",
    city: "Mazatlán",
    image: "/clips/tk-r125.jpg",
    video: "/clips/tk-r125.mp4",
    likes: 0,
    comments: [],
    tags: ["banda", "sinaloa", "parati"],
    sound: "Sonido original",
    soundArtist: "charly_moreno_",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r126",
    user: "denniscotadance",
    displayName: "Dennis Cota",
    caption: "Paso fácil de quebradita. Vía @denniscotadance",
    city: "Guadalajara",
    image: "/clips/tk-r126.jpg",
    video: "/clips/tk-r126.mp4",
    likes: 0,
    comments: [],
    tags: ["quebradita", "baile", "parati"],
    sound: "Sonido original",
    soundArtist: "denniscotadance",
    series: "DailyLife",
    country: "MX",
  },
  {
    id: "tk-r127",
    user: "dateungusto_mx",
    displayName: "Date un gusto",
    caption: "Champurrado de guayaba. Vía @dateungusto_mx",
    city: "Ciudad de México",
    image: "/clips/tk-r127.jpg",
    video: "/clips/tk-r127.mp4",
    likes: 0,
    comments: [],
    tags: ["champurrado", "comida", "parati"],
    sound: "Sonido original",
    soundArtist: "dateungusto_mx",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r128",
    user: "arumalaxola",
    displayName: "Aruma",
    caption: "Xoloitzcuintle, de chiquitín. Vía @arumalaxola",
    city: "Ciudad de México",
    image: "/clips/tk-r128.jpg",
    video: "/clips/tk-r128.mp4",
    likes: 0,
    comments: [],
    tags: ["xolo", "perro", "parati"],
    sound: "Sonido original",
    soundArtist: "arumalaxola",
    series: "DailyLife",
    country: "MX",
  },
,
  {
    id: "tk-r129",
    user: "mbmarcobeteta",
    displayName: "MarcoBeteta",
    caption: "Si buscas buen pastor en la CDMX, guarda esta lista. Vía @mbmarcobeteta",
    city: "Ciudad de México",
    image: "/clips/tk-r129.jpg",
    video: "/clips/tk-r129.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "mbmarcobeteta",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r133",
    user: "perrito_taquero",
    displayName: "Perrito Taquero",
    caption: "Los 10 mejores tacos al pastor de la CDMX. Vía @perrito_taquero",
    city: "Ciudad de México",
    image: "/clips/tk-r133.jpg",
    video: "/clips/tk-r133.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "perrito_taquero",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r134",
    user: "christiansolorzanosol",
    displayName: "Christian Sol",
    caption: "Tacos al pastor. Así, sin más. Vía @christiansolorzanosol",
    city: "Ciudad de México",
    image: "/clips/tk-r134.jpg",
    video: "/clips/tk-r134.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "parati"],
    sound: "Sonido original",
    soundArtist: "christiansolorzanosol",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r135",
    user: "soydanyzuco",
    displayName: "Dany Zuco",
    caption: "Pastor malo en CDMX no es noticia. El bueno, hay que cazarlo. Vía @soydanyzuco",
    city: "Ciudad de México",
    image: "/clips/tk-r135.jpg",
    video: "/clips/tk-r135.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "soydanyzuco",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r136",
    user: "ibngarcia",
    displayName: "Iban Garcia",
    caption: "Tacos al pastor 2.0. Vía @ibngarcia",
    city: "Ciudad de México",
    image: "/clips/tk-r136.jpg",
    video: "/clips/tk-r136.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "parati"],
    sound: "Sonido original",
    soundArtist: "ibngarcia",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r137",
    user: "mbmarcobeteta",
    displayName: "MarcoBeteta",
    caption: "Lista de pastor en la CDMX. Guárdala. Vía @mbmarcobeteta",
    city: "Ciudad de México",
    image: "/clips/tk-r137.jpg",
    video: "/clips/tk-r137.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "mbmarcobeteta",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r138",
    user: "ibngarcia",
    displayName: "Iban Garcia",
    caption: "Primera vez con el trompo. Vía @ibngarcia",
    city: "Ciudad de México",
    image: "/clips/tk-r138.jpg",
    video: "/clips/tk-r138.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "parati"],
    sound: "Sonido original",
    soundArtist: "ibngarcia",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r139",
    user: "fryesir73",
    displayName: "Fryesir",
    caption: "Tacos a dos dólares. México no miente. Vía @fryesir73",
    city: "Ciudad de México",
    image: "/clips/tk-r139.jpg",
    video: "/clips/tk-r139.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "parati"],
    sound: "Sonido original",
    soundArtist: "fryesir73",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r140",
    user: "el_javi_corona",
    displayName: "Javi Corona",
    caption: "Planchados al pastor en MixTacos. Vía @el_javi_corona",
    city: "Ciudad de México",
    image: "/clips/tk-r140.jpg",
    video: "/clips/tk-r140.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "pastor", "parati"],
    sound: "Sonido original",
    soundArtist: "el_javi_corona",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r141",
    user: "chuchito.garrido",
    displayName: "Chuchito Garrido",
    caption: "Cuatro taquerías que sí en la CDMX. Vía @chuchito.garrido",
    city: "Ciudad de México",
    image: "/clips/tk-r141.jpg",
    video: "/clips/tk-r141.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "chuchito.garrido",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r142",
    user: "tijuanationmx",
    displayName: "TIJUANATION",
    caption: "Unos tacos como deben ser. Taco Naco. Vía @tijuanationmx",
    city: "Tijuana",
    image: "/clips/tk-r142.jpg",
    video: "/clips/tk-r142.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "Tijuana", "parati"],
    sound: "Sonido original",
    soundArtist: "tijuanationmx",
    series: "FoodLab",
    country: "MX",
  },
  {
    id: "tk-r143",
    user: "sunslanguagejourney",
    displayName: "Sun",
    caption: "Pastor y una Coca en CDMX. Vía @sunslanguagejourney",
    city: "Ciudad de México",
    image: "/clips/tk-r143.jpg",
    video: "/clips/tk-r143.mp4",
    likes: 0,
    comments: [],
    tags: ["tacos", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "sunslanguagejourney",
    series: "FoodLab",
    country: "MX",
  },
,
  {
    id: "tk-r144",
    user: "ricardoalonsoes",
    displayName: "Ricardo Alonso",
    caption: "Plaza Garibaldi. Mira hasta el final. Vía @ricardoalonsoes",
    city: "Ciudad de México",
    image: "/clips/tk-r144.jpg",
    video: "/clips/tk-r144.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "Garibaldi", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "ricardoalonsoes",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r145",
    user: "mariachigaribaldijd",
    displayName: "Mariachi Garibaldi",
    caption: "El piteado, las trompetas. Garibaldi. Vía @mariachigaribaldijd",
    city: "Ciudad de México",
    image: "/clips/tk-r145.jpg",
    video: "/clips/tk-r145.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "Garibaldi", "parati"],
    sound: "Sonido original",
    soundArtist: "mariachigaribaldijd",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r146",
    user: "meryvalencia21",
    displayName: "Mery Valencia",
    caption: "En la plaza, con el mariachi. Vía @meryvalencia21",
    city: "Ciudad de México",
    image: "/clips/tk-r146.jpg",
    video: "/clips/tk-r146.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "meryvalencia21",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r147",
    user: "magalyssantana0",
    displayName: "Magalys",
    caption: "Plaza Garibaldi, México. Vía @magalyssantana0",
    city: "Ciudad de México",
    image: "/clips/tk-r147.jpg",
    video: "/clips/tk-r147.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "Garibaldi", "parati"],
    sound: "Sonido original",
    soundArtist: "magalyssantana0",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r148",
    user: "garibaldi_show",
    displayName: "Mariachi Garibaldi de Montero",
    caption: "Flores, mariachi, y la cumpleañera. Vía @garibaldi_show",
    city: "Ciudad de México",
    image: "/clips/tk-r148.jpg",
    video: "/clips/tk-r148.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "parati"],
    sound: "Sonido original",
    soundArtist: "garibaldi_show",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r149",
    user: "kristinamac1990",
    displayName: "KrisMac",
    caption: "Mariachi Garibaldi en vivo. Vía @kristinamac1990",
    city: "Ciudad de México",
    image: "/clips/tk-r149.jpg",
    video: "/clips/tk-r149.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "parati"],
    sound: "Sonido original",
    soundArtist: "kristinamac1990",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r150",
    user: "anaira313",
    displayName: "Ari Castillo",
    caption: "Mejor me voy — y el mariachi sigue. Vía @anaira313",
    city: "Ciudad de México",
    image: "/clips/tk-r150.jpg",
    video: "/clips/tk-r150.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "parati"],
    sound: "Sonido original",
    soundArtist: "anaira313",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r151",
    user: "isidro.mx",
    displayName: "Isidro",
    caption: "Mariachi Garibaldi. Vía @user5104315043454",
    city: "Ciudad de México",
    image: "/clips/tk-r151.jpg",
    video: "/clips/tk-r151.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "parati"],
    sound: "Sonido original",
    soundArtist: "isidro.mx",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r152",
    user: "relampagodelcielo",
    displayName: "Relámpago del Cielo",
    caption: "Cincuenta años de mariachi. Vía @relampagodelcielo",
    city: "Ciudad de México",
    image: "/clips/tk-r152.jpg",
    video: "/clips/tk-r152.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "parati"],
    sound: "Sonido original",
    soundArtist: "relampagodelcielo",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r153",
    user: "quibor.tv",
    displayName: "Quibor TV",
    caption: "Mariachi Garibaldi para el Día de las Madres. Vía @quibor.tv",
    city: "Ciudad de México",
    image: "/clips/tk-r153.jpg",
    video: "/clips/tk-r153.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "parati"],
    sound: "Sonido original",
    soundArtist: "quibor.tv",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r154",
    user: "graysonmacdonaldyoutube",
    displayName: "Grayson MacDonald",
    caption: "Primer día en la CDMX. Garibaldi se oye desde la calle. Vía @graysonmacdonaldyoutube",
    city: "Ciudad de México",
    image: "/clips/tk-r154.jpg",
    video: "/clips/tk-r154.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "CDMX", "parati"],
    sound: "Sonido original",
    soundArtist: "graysonmacdonaldyoutube",
    series: "FestivalFiles",
    country: "MX",
  },
  {
    id: "tk-r155",
    user: "mariachigaribaldijd",
    displayName: "Mariachi Garibaldi",
    caption: "¿Dónde están los solteros? Plaza Garibaldi. Vía @mariachigaribaldijd",
    city: "Ciudad de México",
    image: "/clips/tk-r155.jpg",
    video: "/clips/tk-r155.mp4",
    likes: 0,
    comments: [],
    tags: ["mariachi", "Garibaldi", "parati"],
    sound: "Sonido original",
    soundArtist: "mariachigaribaldijd",
    series: "FestivalFiles",
    country: "MX",
  },
];
